export const newDashboardLabels = {
  langz: {
    eng: {
      dir: "ltr",
      months: {
        "01": {
          full: "January",
          half: "Jan",
        },
        "02": {
          full: "February",
          half: "Feb",
        },
        "03": {
          full: "March",
          half: "Mar",
        },
        "04": {
          full: "April",
          half: "Apr",
        },
        "05": {
          full: "May",
          half: "May",
        },
        "06": {
          full: "June",
          half: "Jun",
        },
        "07": {
          full: "July",
          half: "Jul",
        },
        "08": {
          full: "August",
          half: "Aug",
        },
        "09": {
          full: "September",
          half: "Sep",
        },
        "10": {
          full: "October",
          half: "Oct",
        },
        "11": {
          full: "November",
          half: "Nov",
        },
        "12": {
          full: "December",
          half: "Dec",
        },
      },
      paidBill: "Paid Bill",
      unpaidBill: "Unpaid Bill",
      partialPaidBill: "Partially Paid Bill",
      sar: "SAR",
      title: "Quick Actions",
      t1: "Customize",
      t2: "All",
      subtitle: {
        t1: "VAT Return",
        t2: "Tax Certificates",
        t3: "Bill Payments",
        t4: "Zakat Return",
      },
      title2: "Bills",
      title3: "Returns",
      title4: "Tax Types",
      bills: {
        t1: "Paid",
        t2: "Unpaid",
        t3: "Partially",
      },
      returns: {
        t1: "Submitted",
        t2: "Unsubmitted",
        t3: "Overdue",
      },
      subtitle2: {
        t1: "VAT",
        t2: "Excesie",
        t3: "Zakat",
        t4: "Witholding",
      },
      title5: "Help",
      subtitle3: {
        t1: "Contact Us",
        t2: "FAQs",
        t3: "Chat",
      },
      title6: "Inbox",
      subtitle4: {
        t1: "Mail Title 1",
        d1: "Mail Description can ...",
      },
      title7: "Next Commitments",
      subtitle5: {
        t1: "Upcoming com.....1",
        d1: "Commitment Details..",
      },
      c1: {
        t1: "Instalment Plans",
        t2: "VAT",
        t3: "4793187498192",
        t4: "200.000,00 SAR ",
        t5: "Next Payment Due",
        t6: "24 January",
        t7: "10.000,00 SAR ",
      },
      c2: {
        t1: "Tax Balances",
        t2: "Zakat",
        t3: "Zakat Debit",
        t4: "1,500.00 SAR",
        t5: "- 180.00 SAR",
        t6: "Zakat Credit",
        t7: "Total Zakat Balance",
        t8: "1,320.00 SAR",
      },
      Auditor1: {
        title: "Taxpayer Activities",
        t1: "Licence / CR Number",
        t2: "Taxpayer Type",
        t3: "TIN",
        t4: "Name",
        t5: "Mobile Number",
        t6: "Email",
      },
      Auditor2: {
        title: "Taxpayer Allocation",
        t1: "User",
        t2: "Branch",
        t3: "Linked Taxpayer",
        t4: "Link Activities",
      },
      Auditor3: {
        title: "Approvals & Rejections",
        t1: "Abu Farwa Industries Co.",
        t2: "Zakat & CIT",
        t3: "Pending",
        t4: "STC",
        t5: "VAT",
        t6: "Approved",
        t7: "Saudia",
        t8: "Excise Tax",
        t9: "Rejected",
      },
      Auditor4: {
        title: "Branch Information",
        t1: "Hardy Store",
        t2: "Main Branch",
        t3: "Zaed Store",
        t4: "Sub Branch",
        t5: "Harby Mostafa",
        t6: "Sub Branch",
      },
      Auditor5: {
        title: "Employee Administration",
        t1: "Hardy Store",
        t2: "Main Branch",
        t3: "Zaed Store",
        t4: "Sub Branch",
        t5: "Harby Mostafa",
        t6: "Sub Branch",
      },
    },
    arb: {
      dir: "rtl",
      months: {
        "01": {
          full: "يناير",
          half: "يناير",
        },
        "02": {
          full: "فبراير",
          half: "فبراير",
        },
        "03": {
          full: "مارس",
          half: "مارس",
        },
        "04": {
          full: "ابريل",
          half: "ابريل",
        },
        "05": {
          full: "مايو",
          half: "مايو",
        },
        "06": {
          full: "يونيو",
          half: "يونيو",
        },
        "07": {
          full: "يوليو",
          half: "يوليو",
        },
        "08": {
          full: "أغسطس",
          half: "أغسطس",
        },
        "09": {
          full: "سبتمبر",
          half: "سبتمبر",
        },
        "10": {
          full: "أكتوبر",
          half: "أكتوبر",
        },
        "11": {
          full: "نوفمبر",
          half: "نوفمبر",
        },
        "12": {
          full: "ديسمبر",
          half: "ديسمبر",
        },
      },
      paidBill: "الفواتير المدفوعة",
      unpaidBill: "الفواتير غير المدفوعة",
      partialPaidBill: "الفواتير المدفوعة جزئيا",
      sar: "ريال سعودي",
      title: "الوصول السريع",
      t1: "تعديل",
      t2:"الكل",
      subtitle: {
        t1: "إقرارات ضريبة القيمة المضافة",
        t2: "الشهادات الضريبية",
        t3: "دفع الفواتير",
        t4: "دفع الفواتير",
      },
      title2: "الفواتير",
      title3: "الإقرارات",
      title4: "أنواع الضرائب",
      bills: {
        t1: "مدفوعة",
        t2: "جزئيا",
        t3: " غير مدفوعة",
      },
      returns: {
        t1: "تم تقديمه",
        t2: "لم يتم تقديمه",
        t3: "متأخرة",
      },
      subtitle2: {
        t1: "ضريبة القيمة المضافة",
        t2: "ضريبة السلع الإنتقائية",
        t3: "الزكاة",
        t4: "ضريبة الاستقطاع",
      },
      title5: "المساعدة",
      subtitle3: {
        t1: "تواصل معنا",
        t2: "الأسئلة الشائعة",
        t3: "المحادثة",
      },
      title6: "صندوق الوارد",
      subtitle4: {
        t1: "عنوان البريد",
        d1: "محتوى البريد...........",
      },
      title7: "الإلتزامات",
      subtitle5: {
        t1: "لاتوجد إلتزامات قادمة",
        d1: "محتوى البريد...........",
      },
      c1: {
        t1: "خطط التقسيط",
        t2: "ضريبة القيمة المضافة",
        t3: "4793187498192",
        t4: "200.000,00 SAR ",
        t5: "المدفوعات القادمة  ",
        t6: "24 يناير",
        t7: "10.000,00 SAR ",
      },
      c2: {
        t1: "ارصدة الضريبة",
        t2: "الزكاة",
        t3: "العمليات المدينة",
        t4: "1,500.00 SAR",
        t5: "- 180.00 SAR",
        t6: "العمليات الدائنة",
        t7: "الرصيد",
        t8: "1,320.00 SAR",
      },
      Auditor1: {
        title: "نشاطات المكلف",
        t1: "رخصة أو رقم السجل التجاري",
        t2: "نوع المكلف",
        t3: "TIN",
        t4: "نوع المكلف",
        t5: "الجوال",
        t6: "البريد الالكتروني",
      },
      Auditor2: {
        title: "إعدادت المكلف",
        t1: "مستخدم",
        t2: "فرع",
        t3: "المكلفين المرتبطين",
        t4: "ربط النشاطات",
      },
      Auditor3: {
        title: "الموافقات والرفض",
        t1: "Abu Farwa Industries Co.",
        t2: "الزكاة و ضريبة الدخل",
        t3: "معلقه",
        t4: "STC",
        t5: "ضريبة القيمة المضافة",
        t6: "تمت الموافقه",
        t7: "المملكة العربية السعودية",
        t8: "ضريبة السلع الانتقائية",
        t9: "مرفوضة",
      },
      Auditor4: {
        title: "إدارة الفروع",
        t1: "Hardy Store",
        t2: "Main Branch",
        t3: "Zaed Store",
        t4: "Sub Branch",
        t5: "Harby Mostafa",
        t6: "Sub Branch",
      },
      Auditor5: {
        title: "إدارة الموظفين",
        t1: "Hardy Store",
        t2: "Main Branch",
        t3: "Zaed Store",
        t4: "Sub Branch",
        t5: "Harby Mostafa",
        t6: "Sub Branch",
      },
    },
  },
};
