export const fieldCasesConstants = {
  langz: {
    eng: {
      dir: "ltr",
      dashboard: {
        title: "Quick Actions",
        t1: "Customize",
        subtitle: {
          t1: "VAT Return",
          t2: "Tax Certificates",
          t3: "Bill Payments",
          t4: "Zakat Return",
        },
        title2: "Bills",
        title3: "Returns",
        title4: "Tax Types",

        returns: {
          t1: "Submitted",
          t2: "Unsubmitted",
          t3: "Overdue",
        },
        subtitle2: {
          t1: "VAT",
          t2: "Excesie",
          t3: "Zakat",
          t4: "Witholding",
        },
        title5: "Help",
        subtitle3: {
          t1: "Contact Us",
          t2: "FAQs",
          t3: "Chat",
        },
        title6: "Inbox",
        subtitle4: {
          t1: "Mail Title 1",
          d1: "Mail Description can ...",
        },
        title7: "Next Commitments",
        subtitle5: {
          t1: "Upcoming com.....1",
          d1: "Commitment Details..",
        },
        title8: "VAT Field Inspection",
      },

      fieldInspectionCases: {
        t1: "Field Inspection Cases",
        t2: "Back",
        t3: "In Process",
        t4: "Tax Management",
        t5: "Excise Tax Services",
        t6: "<",
        t7: ">",
        t8: "Field Inspection Cases Details",
        t9: "Field Inspection Case",
        c1: {
          t1: "Amount",
          t2: "Status",
          t3: "Case Number",
          t4: "Inspection Date",
        },
        c2: {
          t1: "Inspection Case Number",
          t2: "Inspection date(Date of Inspection)",
          t3: "City",
          t4: "Violation Category",
          t5: "District",
          t6: "Violation Description",
          t7: "Street Name",
          t8: "Penalty amount (SAR)",
          t9: "Taxpayer Name",
          t10: "TIN",
          t11: "Taxpayer Representative Position",
          t12: "Taxpayer representative",
          t13: "Payment Status",
          t14: "Violated Items types",
        },
        trans: {
          downloadHeader: "Download Statement",
          from: "From",
          to: "To",
          downloadSubheading: "Select a date range and download the Statement",
          statement: "Statement Date",
          download: "Download",
          waers:"SAR"
        },
      },
      months: {
        "01": "January",
        "02": "February",
        "03": "March",
        "04": "April",
        "05": "May",
        "06": "June",
        "07": "July",
        "08": "August",
        "09": "September",
        "10": "October",
        "11": "November",
        "12": "December",
      },
    },
    arb: {
      dir: "rtl",
      dashboard: {
        title: "الوصول السريع",
        t1: "تعديل",
        subtitle: {
          t1: "إقرارات ضريبة القيمة المضافة",
          t2: "الشهادات الضريبية",
          t3: "دفع الفواتير",
          t4: "دفع الفواتير",
        },
        title2: "الفواتير",
        title3: "الإقرارات",
        title4: "أنواع الضرائب",

        fieldInspectionCases: {
          title8: "التفتيش الميداني لضريبة القيمة المضافة",
        },
        returns: {
          t1: "تم تقديمها",
          t2: "لم يتم تقديمها  ",
          t3: "متأخرة ",
        },
        subtitle2: {
          t1: "ضريبة القيمة المضافة",
          t2: "ضريبة السلع الإنتقائية",
          t3: "الزكاة",
          t4: "ضريبة الاستقطاع",
        },
        title5: "المساعدة",
        subtitle3: {
          t1: "تواصل معنا",
          t2: "الأسئلة الشائعة",
          t3: "المحادثة",
        },
        title6: "صندوق الوارد",
        subtitle4: {
          t1: "عنوان البريد",
          d1: "محتوى البريد...........",
        },
        title7: "الإلتزامات",
        subtitle5: {
          t1: "لاتوجد إلتزامات قادمة",
          d1: "محتوى البريد...........",
        },
      },

      fieldInspectionCases: {
        t1: "حالات الضبط الميدانى",
        t2: "رجوع",
        t3: "تحت المعالجة",
        t4: "إدارة الضرائب",
        t5: "خدمات الضرائب الانتقائية",
        t6: ">",
        t7: "<",
        t8:  "تفاصيل حالات الضبط الميداني",
        t9: "حالات الضبط الميدانى",
        c1: { 
          t1: "كمية",
          t2: "الحالة",
          t3: "رقم القضية",
          t4: "تاريخ الفحص",
        },
        c2: {
          t1: "رقم حالة التفتيش",
          t2: "تاريخ التفتيش (تاريخ التفتيش)",
          t3: "مدينة",
          t4: "فئة الانتهاك",
          t5: "منطقة",
          t6: "وصف الانتهاك",
          t7: "اسم الشارع",
          t8: "مبلغ الغرامة (ريال سعودي)",
          t9: "اسم المكلف",
          t10: "يصدق",
          t11: "منصب المكلف",
          t12: "ممثل المكلفين",
          t13: "حالة السداد",
          t14: "أنواع العناصر المخالفة",
        },
        trans: {
          downloadHeader: "تحميل الكشف",
          from: "من",
          to: "إلى",
          downloadSubheading: "الرجاء تحديد الفترة لتنزيل الكشف",
          statement: "تاريخ كشف الحساب",
          download: "تحميل",
          waers:"ريال سعودي"
        },
      },
      months: {
        "01": "يناير",
        "02": "فبراير",
        "03": "مارس",
        "04": "ابريل",
        "05": "مايو",
        "06": "يونيو",
        "07": "يوليو",
        "08": "أغسطس",
        "09": "سبتمبر",
        "10": "أكتوبر",
        "11": "نوفمبر",
        "12": "ديسمبر",
      },
    },
  },
};

export const ApiFieldCasesConstants = {
  getFieldCasesData: "sap/opu/odata/SAP/Z_ET_INSP_PENALTY_SRV/HeaderSet",
};
