export const InstallmentPlan = {
  langz: {
    eng: {
      dir: "ltr",
      screen1: {
        title: "Instalment Plans",
        tab1: "All Instalment Plans",
        tab2: "Zakat",
        znc: "Zakat & CIT",
        tab3: "VAT",
        tag1: "Active",
        int: "Income Tax",
        tag2: "Requested",
        tag3: "Cancelled",
        card1: "Request Instalment Plan",
        srNo: "Sr no",
        taxType: "Tax Type",
        pr_installmet: "Periodic Instalment Amount",
        due_date: "Due Date",
        dueAmtPyb: "Down Payment Amount Payable - ",
        fr1: "Monthly",
        fr2: "Quaterly",
        fr3: "Half Yearly",
        fr4: "Yearly",
        next_dt: "Next Payment Due",
        status: "Status",
        sar: "SAR",
        proceed: "To proceed with your instalments plan request you have to submit all the due returns and pay the required Zakat / Tax amount or add the new invoices to the instalments request",
        taxPay: "Dear Taxpayer {0},TIN {1}",
        filesizeMessage: "File size should not be more than 5 MB.",
        invalidFormat: "Upload files with allowed extensions only",
        fileAlreayExists: "File with the same name already exists",
        maxNoOfFiles: "Maximum no. of 10 attachments can be uploaded.",
        attFileNmSize: "File name must not exceed 100 characters.",
        attachBankStatement: "ATTACH BANK STATEMENTS FOR THE LAST 3 MONTHS",
        attachFinStatement: "ATTACH FINANCIAL STATEMENTS FOR THE LAST 3 YEARS",
        retFbNum: "Return FBN",
        retTxTyp: "Return Tax Type",
        retPerDes: "Return Period Desc.",
        retCreDt: "Return Creation date",
        retDueDt: "Return Due date",
        error: "Error",
        close: "Close"
      },
      filter: {
        header: "Filter",
        all: "All",
        label1: "Type",
        label2: "Status",
        label3: "Instalment Period",
        label4: "Down Payment Amount",
        label5: "Invoice Amount",
        button: "Apply",
        t5: "From",
        t6: "To",
        fil1: "Submitted",
        fil2: "Approved",
        fil3: "In Process",
        fil4: "Cancelled",
        fil5: "Draft",
        fil6: "Additional Information Required",
      },
      screen2: {
        title1: "Select Type",
        placeholder1: "Choose the Tax type to request a instalment plan",
        title2: "Select Bills",
        placeholder2:
          "Select the SADAD bills you wish to include in the instalment agreement",
        placeholder3: "Provide the supporting documents",
        title4: "Summary",
        placeholder4: "Review the below information",
        card_label1: "Bank Statements for the last 3 months",
        card_label2: "Financial Statements for the last 3 years",
        back: "Back",
        bills: "Bills",
        bill: "Bill",
        invmsg: "There are no invoices to be added to the installments plan request.",
        inst_agr: "Instalment Agreement",
        attch: "Attachment",
        caption: "Amendment by GAZT",
        sadNumber: "SADAD Number",
        tax_period: "Tax Period",
        amt: "Total Amount",
        amount: "Amount",
        tot: "Total",
        rsn: "Reason for requesting Instalment",
        button1: "Continue",
        ins_sch: "Instalment Schedule",
        set_ins_plan: "Set up your instalment plan details",
        min: "Min",
        max: "Max",
        req: "required",
        edit: "Edit",
        freq: "Frequency",
        no_ins: "Number of Instalments",
        file_op1: "Drag and drop file to upload documentation",
        file_manually: "Fill Manually",
        items: "Items",
        y: "Year",
        y1: "Year 1",
        y2: "Year 2",
        y3: "Year 3",
        candb: "Cash + Bank",
        sFInv: "Short Term investment",
        debts: "Debtors",
        invt: "Inventory",
        tCasset: "Total Current Assets",
        zandT: "Zakat and Tax",
        tCLiab: "Total Current Liabilities",
        revenue: "Revenue",
        net_inc: "Net Income",
        cashFlow: "Not Cash Flow from Operation",
        prf_ratio: "Profability Ratio (10/9)",
        cash_ratio: "Cash Ratio (2+3)/8 ",
        attachments: "Attachments",
        pr_amt: "Periodic Instalment",
        confirm: "Confirm",
        success_msg1: "Your Zakat Instalment Plan is successfully submitted",
        success_msg2: "Your CIT Instalment Plan is successfully submitted",
        ref_num: "Reference Number",
        dwnld_cnfrm: "Download Confirmation",
        display_ins: "Display Instalment Details",
        go_dashboard: "Go To Dashboard",
        ack51: "Kindly complete the payment within ",
        ack52: "7 days",
        ack53: "to prevent the cancellation of your instalment request.",
        tooltip1: "(Net Income/Revenue)",
        tooltip2:
          "{((Cash + Bank)+Short Term Investment)/Total Current Liabilities}",
        dwldform: "Download Form",
      },
      zakatSc: {
        ins_pln_set: "Instalment Plan Details",
        ins_dtls: "Instalment Details",
        rq_dt: "Request Date",
        due_amt: "Due Amount",
        ins_amt: "Instalment Amount",
        bill_ty: "Bill Type",
        revk: "Revoke",
        invno: "Invoice Number",
        rsn1: "Financial  Crisis - Inability To settle Dues",
        rsn2: "Dispute in favor of GAZT",
        rsn3: "Other Reason",
        t1: "Verification Code",
        title: "Please enter the verification code sent to mobile number",
        verifyTitle: "Resend Verification code",
        notes: "Notes",
        details: "Complete the details below",
        eNotesMis: "Please maintain notes",
        Okay: "Okay",
        cancel: "Cancel",
        Wrongcodemsg: "Verfication code is incorrect. Please try again.",
        success_msg1: "Your Zakat Instalment Plan is successfully revoked",
        rAppNo: "Application No.",
        desc: "Description",
        msgStrip: "You need to restart the process after attempting to enter three wrong verification codes",
        verifyError: "Verification is incorrect, Please try again",
        RevcfMsg1: "Dear Taxpayer, when your request to revoke the instalments plan",
        RevcfMsg2: "all the original invoices will reissued with the residual amounts that needs to be paid and those invoices cannot be added to any future instalments plan."

      },
      instruction: {
        mStep1: "INSTRUCTIONS",
        insthdr1: "Instructions for Instalment Plan Request Form",
        inst1:
          "1. I acknowledge that I do not have sufficient liquidity to pay the full amount.",
        inst2:
          "2. I pledge to provide the General Authority for Zakat & Tax with all recent bank statements of the business activity, as well as my personal account statements for the past three months.",
        inst3:
          "3. I pledge to provide the General Authority for Zakat & Tax with any documents that are requested for the purpose of processing the application.",
        inst4:
          "4. The General Authority for Zakat & Tax has the right to estimate the amount and period of the instalment plan, as appropriate.",
        inst5:
          "5. I pledge to pay at least 20% of total debts that requested for instalment.",
        inst6:
          "6. The General Authority for Zakat & Tax has the right to cancel the instalment plan, in case of having financial unsuitability to pay the full amount of the dues.",
        inst7:
          "7. I acknowledge that In case of default in paying two sequential instalmentts, the General Authority for Zakat & Tax has the right to cancel the instalment plan, and no other instalment plan could be requested for the same invoices.",
        inst8:
          "8. The General Authority for Zakat & Tax has the right to implement the collection procedures, in the case of cancellation of the instalment plan.",
        inst9:
          "9. The General Authority for Zakat & Tax has the right to cancel the instalment plan, in case of reassessment of the amount that has been approved for the instalment plan.",
        checkLable: "I agree",
      },
    },
    arb: {
      dir: "rtl",
      screen1: {
        title: "خطة التقسيط",
        tab1: "جميع خطط التقسيط",
        tab2: "الزكاة",
        tab3: "ضريبة القيمة المضافة",
        tag1: "نشط",
        tag2: "المقدمة",
        tag3: "السابقة",
        znc: "الزكاة وضريبة الدخل",
        int: "ضريبة الدخل",
        card1: "طلب خطة تقسيط",
        srNo: "الرقم التسلسلي",
        taxType: "نوع الضريبة",
        pr_installmet: "مبلغ القسط الدوري",
        dueAmtPyb: "الدفعة الأولى المبلغ المستحق -",
        due_date: "تاريخ الاستحقاق",
        fr1: "شهري",
        fr2: "ربع سنوي",
        fr3: "نصف سنوي",
        fr4: "سنويا",
        next_dt: "تاريخ الاستحقاق القادم",
        status: "الحالة",
        sar: "ريال سعودي",
        proceed: "لتتمكن من الاستمرار في تقديم طلب التقسيط ، يلزم عليكم تقديم كافة الإقرارت المستحقة والسداد بموجبها أو اضافتها لطلب التقسيط.",
        taxPay: "عزيزي المكلف {0},الرقم المميز {1}",
        attFileNmSize: "اسم الملف يجب ان لا يزيد عن 100 حرف",
        filesizeMessage: "يجب أن يكون حجم الملف أقل من 5 ميجا بايت.",
        invalidFormat: "الرجاء استخدام صيغ الملفات المسموح بها فقط",
        fileAlreayExists: "يوجد ملف بنفس الاسم مرفق مسبقا",
        maxNoOfFiles: "لا يمكن تحميل أكثر من 10 مرفقات",
        attachBankStatement: "أرفق كشف الحساب البنكي لآخر 3 أشهر *",
        attachFinStatement: "أرفق البيانات المالية لآخر 3 سنوات",
        retFbNum: "رقم الإقرار",
        retTxTyp: "نوع الضريبة",
        retPerDes: "سنة الإقرار",
        retCreDt: "تاريخ انشاء الإقرار",
        retDueDt: "تاريخ استحقاق الإقرار",
        error: "خطأ",
        close: "إغلاق"
      },
      filter: {
        header: "فلتر",
        all: "الجميع",
        label1: "اكتب",
        label2: "الحالة",
        label3: "Installment Period",
        label4: "مبلغ الدفعة المقدمة",
        label5: "مبلغ الفاتورة",
        button: "تقديم",
        t5: "من",
        t6: "إلى",
        fil1: "مقدمة",
        fil2: "موافقة",
        fil3: "قيد المراجعة",
        fil4: "تم إلغائها",
        fil5: "مسودة",
        fil6: "مطلوب بيانات اضافية",
      },
      screen2: {
        title1: "اختر النوع",
        placeholder1: "اختر نوع الضريبة لطلب خطة التقسيط",
        title2: "اختر الفاتورة",
        placeholder2: "حدد فواتير سداد التي ترغب في تضمينها في اتفاقية التقسيط",
        placeholder3: "تقديم المستندات الداعمة",
        title4: "ملخص",
        placeholder4: "مراجعة البيانات التالية",
        card_label1: "كشف حساب بنكي لآخر 3 أشهر",
        card_label2: "البيانات المالية لآخر 3 سنوات",
        bills: "الفواتير",
        bill: "الفاتورة",
        invmsg: "لا توجد فواتير لإضافتها الى طلب خطة التقسيط",
        back: "رجوع",
        inst_agr: "اتفاقية التقسيط",
        attch: "المرفق",
        caption: "تم التعديل من قبل الهيئة",
        sadNumber: "رقم فاتورة سداد",
        tax_period: "الفترة الضريبية",
        amt: "المبلغ الإجمالي",
        amount: "المبلغ",
        tot: "المجموع",
        rsn: "سبب طلب القسط",
        button1: "استمر",
        ins_sch: "جدول الأقساط",
        set_ins_plan: "إعداد تفاصيل خطة التقسيط",
        min: "الحد الأدنى",
        max: "الحد الأعلى",
        req: "required",
        edit: "تعديل",
        freq: "التكرار",
        no_ins: "عدد الأقساط",
        file_op1: "سحب وإفلات الملف لتحميل الوثيقة",
        file_manually: "تعبئة يدوية",
        items: "البنود",
        y: "سنة",
        y1: "سنة -1",
        y2: "سنة -2",
        y3: "سنة -3",
        candb: "النقدية + البنك",
        sFInv: "استثمار قصير المدى",
        debts: "المدينين",
        invt: "المخزون",
        tCasset: "إجمالي الأصول الحالية",
        zandT: "الزكاة والضريبة",
        tCLiab: "إجمالي الالتزامات الحالية",
        revenue: "إيرادات",
        net_inc: "صافي الدخل",
        cashFlow: "صافي التدفق النقدي من العملية",
        prf_ratio: "معدل الربحية (10/9)",
        cash_ratio: "نسبة النقد (2 + 3) / 8",
        attachments: "المرفقات",
        pr_amt: "القسط الدوري",
        confirm: "تأكيد",
        success_msg1: "تم استلام خطة تقسيط الزكاة بنجاح",
        success_msg2: "تم استلام طلب خطة تقسيط ضريبة الدخل بنجاح",
        ref_num: "الرقم المرجعي",
        dwnld_cnfrm: "تنزيل اشعار",
        display_ins: "عرض تفاصيل الدفعة‎",
        go_dashboard: "الانتقال الى الشاشة الرئيسية",
        ack51: "يرجى سداد المبلغ خلال ",
        ack52: "7 أيام",
        ack53: "تجنباً لإلغاء طلب التقسيط الخاص بكم",
        tooltip1: "(صافي الدخل/إيرادات)",
        tooltip2:
          "{((النقدية + البنك)+استثمار قصير المدى)/إجمالي الالتزامات الحالية}",
        dwldform: "تنزيل نموذج ",
      },
      zakatSc: {
        ins_pln_set: "تفاصيل خطة التقسيط",
        ins_dtls: "تفصيل القسط",
        rq_dt: "تاريخ الطلب",
        due_amt: "المبلغ المستحق",
        ins_amt: "مبلغ القسط",
        bill_ty: "نوع الفاتورة",
        revk: "سحب الخطة",
        invno: "رقم الفاتورة",
        rsn1: "الأزمة المالية - عدم القدرة على تسوية الرسوم",
        rsn2: "نزاع لصالح الهيئة",
        rsn3: "ضريبة الدخل",
        t1: "رمز التحقق",
        title: "يرجى إدخال رمز التحقق المرسل من خلال الرسائل النصية إلى رقم الجوال",
        verifyTitle: "إعادة إرسال رمز التحقق",
        notes: "الملاحظات",
        details: "اكمل البيانات التالية",
        eNotesMis: "الرجاء إضافة ملاحظات",
        Okay: "حسنا",
        cancel: "إلغاء",
        Wrongcodemsg: "رمز التحقق غير صحيح. برجاء المحاولة مرة أخري",
        success_msg1: "تم إلغاء طلب خطة تقسيط الزكاة بنجاح",
        rAppNo: "الرقم المرجعي",
        desc: "الوصف",
        verifyError: "رمز التحقق غير صحيح الرجاء المحاولة مره اخرى",
        msgStrip: "تم ادخال رمز تحقق خاطئ الرجاء إعادة العملية مرة اخرى",
        RevcfMsg1: "عزيزي المكلف, عند اكتمال طلبك لإلغاء خطة التقسيط رقم",
        RevcfMsg2: "سيتم إعادة اصدار الفواتير المرتبطة بخطة التقسيط بالمبلغ المتبقي الواجب سداده ولا يمكنك طلب خطة تقسيط أخرى لنفس تلك الفواتير."
      },
      instruction: {
        mStep1: "تعليمات",
        insthdr1: "تعليمات نموذج طلب خطة التقسيط",
        inst1: "1. اقر بأنه لا يوجد لدي سيولة مالية كافيه لسداد المبلغ كاملاً.",
        inst2:
          "2. اتعهد بأن ازود الهيئة العامة للزكاة والدخل بكشوفات حديثة لجميع حسابات النشاط البنكية وكذلك حساباتي الشخصية لآخر ثلاثة أشهر.",
        inst3:
          "3. أتعهد بتزويد الهيئة العامة للزكاة والدخل بأي مستندات يتم طلبها لأغراض دراسة الطلب.",
        inst4:
          "4. للهيئة العامة للزكاة و الدخل الحق في تقدير مبلغ وفترة الاقساط حسب ما تراه مناسباً.",
        inst5:
          "5. أقر بسداد ما لا يقل عن 20 % من قيمة اجمالي المديونيات المطلوب تقسيطها.",
        inst6:
          "6 يحق للهيئة العامة للزكاة والدخل إلغاء خطة التقسيط في حال ثبوت ملائمتكم المالية لسداد كامل المستحقات.",
        inst7:
          "7. اقر بأنه في حال التعثر في سداد قسطين متتاليين، فإنه يحق للهيئة العامة للزكاة والدخل إلغاء خطة التقسيط ولا يمكن طلب خطة تقسيط أخرى لنفس المستحقات.",
        inst8:
          "8.للهيئة العامة للزكاة والدخل الحق في تطبيق إجراءات التحصيل النظامية في حال إلغاء خطة التقسيط.",
        inst9:
          "9. يحق للهيئة العامة للزكاة والدخل الغاء خطة التقسيط في حال وجود إعادة تقييم على المبالغ التي تم الموافقة على تقسيطها.",
        checkLable: "أنا موافق",
      },
    },
  },
};
