export const RefundsConstants = {
  en: {
    dir: "ltr",
    back: "Back",
    refunds: "Refunds",
    allRefunds: "All Refunds",
    sukuk: "Sukuk & Bonds",
    vat: "VAT",
    excise: "Excise Tax",
    search: "Search",
    newSukuk: "New Sukuk & Bonds Refund Request",
    fbNum: "Form Bundle",
    status: "Status",
    newRefund: "New Refund",
    selectOneTax: "Select one tax to proceed",
    vatRefund:"VAT Refund",
    filter:"Filter",
    apply:"Apply",
    reset:"Reset",
    SAR:"SAR",
    filters:{
      INPROCESS:"IN PROCESS",
      COMPLETED :"COMPLETED",
      DRAFT :"DRAFT",
      CANCELED:"CANCELED"
    },
    sukukCard: {
      reassessment: "Reassesment Amount",
      totalOffset: "Total Offset",
      netBalance: "Net Credit Balance",
      requestDate: "Request Date",
    },
    vatCard:{
        FbNumber:"Fb Number",
        RequestDate:"Request Date",
        RequestedAmount:"Requested Amount",
        ReAssessedAmount:"ReAssessed Amount",
        CreditBalance:"Credit Balance",
        Status:"Status",
    },
  },
  ar: {
    dir: "rtl",
    back: "رجوع",
    refunds: "الاستردادات",
    allRefunds: "جميع الاستردادات",
    sukuk: "الصكوك والسندات",
    vat: "ضريبة القيمة المضافة",
    excise: "ضريبة السلع الإنتقائية",
    search: " بحث",
    newSukuk: "طلب استرداد الصكوك والسندات",
    fbNum: "رقم النموذج",
    status: "الحالة",
    newRefund: "طلب استرداد",
    selectOneTax: "الرجاء تحديد ضريبة للمتابعة",
    vatRefund:"استرداد ضريبة القيمة المضافة",
    filter:"فلتر",
    apply:"اكتب",
    reset:"إعادة تعيين",
    SAR:"ريال سعودي",
    filters:{
      INPROCESS:"قيد الدراسة",
      COMPLETED :"مكتمل",
      DRAFT :"مسودة",
      CANCELED:"ملغاة"
    },
    sukukCard: {
      reassessment: "مبلغ التقييم",
      totalOffset: "إجمالي مبلغ المقاصة",
      netBalance: "إجمالي صافي المبلغ الدائن",
      requestDate: "تاريخ الطلب",
    },
    vatCard:{
      FbNumber:"الرقم المرجعي للنموذج",
      RequestDate:"تاريخ الطلب",
      RequestedAmount:"إجمالي المبلغ المطلوب",
      ReAssessedAmount:"المبلغ المعاد تقديره",
      CreditBalance:"الرصيد الدائن بالريال السعودي",
      Status:"الحالة",
  },
  },
};

export const ApiConstants = {
  getAllSukukRefunds: "sap/opu/odata/SAP/ZDP_ZREF_WI_SRV/",
};
