export const RequesToReleaseSecuritiesConstant = {
    eng: {
      dir: "ltr",
      bc1: "Tax Management",
      bc2: "VAT Services",
      bc3: "Release Securities",
      bc4: "Zakat Certificate Request",
      back: "Back",
      fCerNo: "Certificate Number",
      fCerType: "Certificate Type",
      continue: "Continue",
      fTaxPer: "Tax Year",
      tin: 'TIN' ,
      gccIDError:"GCC ID should be between 7-15 digits",
      VATAccNo: 'VAT Account Number',
      idNo: 'Id Number',
      taxpayerName: 'Taxpayer Name',
      address: 'Address',
      iDType: 'ID Type',
      contactPersonName : 'Contact Person Name',
      typeoFsecuritySubmitted: 'Type of security submitted',
      cashRefNo: 'Cash Reference Number',
      securityAmount: 'Security Amount',
      submissionDate: 'Submission Date',
      preferredAccount: 'Preferred Account',
      preferredRefundMethond: 'Preferred Refund Method',
      requestsent: 'Request sent',
      successPageSubHeading: 'Your Release Securities request is submitted successfully',
      name: 'Name',
      applicationtype:"Application type",
      status: 'Status',
      requestNumber: 'Request Number',
      gotoDashboard: 'Go to Dashboard',
      date: 'Date',
      downloadConfirmation: 'Download Confirmation',
      pleaseselectthetypeofsecuritysubmitted: 'Please select the type of security submitted',
      mainoutlitCRLicence:'Main outlet CR/License',
      mainoutlit:'Main Outlet CR/License Name',
      cRLicense:'Main Outlet CR/License Number',
      idMsg: "Please Enter ID",
      dobMsg: "Please Enter DOB",
      textArea: "Character limit exceeded. More text not allowed.",
      gccError: "GCC ID should be between 7-15 digits", 
      cashsecurity:"Cash security",
      bankguarantee:"Bank guarantee",
      Pleaseselectthecasereferencenumber:"Please select the case reference number that the security was submitted for",
      caseReferenceNumber:"Case Reference Number",
      SecurityAmount:"Security Amount",
      Submissiondatestring:"Submission date",
      Pleasespecifyyourpreferredrefundmethod:"Please specify your preferred refund method",
      Cashrefund :"Cash refund(via bank account)",
      CarryforwardofcreditinVATaccount:"Carry forward of credit in VAT account",
      Selectthepreferredaccount:"Select the preferred account",
      addNewRequest:"New request",
      search:"Search",
      continueText :"Continue",
      confirm:"Confirm",
      edit:"Edit",
      NationalIDstartswith1:"National ID starts with 1",
      IqamaIDstartswith2:"Iqama ID starts with 2",
      NationalIDlengthis10digit:"National ID length is 10 digit",
      IqamaIDlengthis10digit:"Iqama ID length is 10 digit",
      pleasecorrectthehighlightedfields:"Please correct the highlighted fields",
      creationdate:'Creation date',
      filter:'Filter',
      apply:'Apply',


      f3: {
        title: "Declaration",
        label1: "ID Type",
        label2: "ID Number",
        label3: "Contact Person Name",
        term: "I acknowledge that above-mentioned information is correct and real as per my knowledge.",
        id1: "National ID",
        id2: "Iqama ID",
        id3: "GCC ID"
    },
  

    modal: {
      dob: "Date of Birth",
      validate: "Validate",
      close: "Close",

  },
  instructionDialogue: {
    title: "Instructions & Conditions",
    p1: "Please fill the requested information for each step. The request cannot be successfully submitted until all of the mandatory fields have been completed. Applicants should ensure that they have the reference or request number related to the decision they would like to review.",
    p2: "Please refer to the FAQ section before filling out the request form.",
    close: "Close",
    checkboxText:"I agree with these conditions and proceed further",
    buttonText:'Release Securities',

},

      menu: [
        {
          //  title: "Taxpayer Details",
          title: "Release Securities",
          //subtitle: "Complete the below details",
          //step: "assets/image/1-st.svg",
        },
        {
          title: "Taxpayer Details",
          subtitle: "Complete the below details",
          step: "assets/image/1-st.svg",
          //step: "assets/image/2-nd.svg",
          
        },
        {
          title: "Security Details",
          subtitle: "Please complete below details",
          step: "assets/image/2-nd.svg",
          //step: "assets/image/3-rd.svg",
        },
        //Declaration
        {
            title: "Declaration",
            subtitle: "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
            step: "assets/image/3-rd.svg",
           // step: "assets/image/4-th.svg",
          },
        {
          title: "Summary",
          subtitle: "Review the information below",
         step: "assets/image/4-th.svg",
         // step: "assets/image/4-th.svg",
        },
  
      ],
  

    },
    arb: {
        dir: "rtl",
        bc1: "إدارة الضريبة",
        bc2: "خدمات ضريبة القيمة المضافة",
        bc3: "الإفراج عن الضمانات",
        bc4: "طلب شهادة الزكاة",
        back: "رجوع",
        NationalIDstartswith1:"يبدأ رقم الهوية الوطنية بالرقم 1",
        NationalIDlengthis10digit:"رقم الهوية الوطنية مكون من 10 أرقام",
      IqamaIDlengthis10digit:"رقم الإقامة مكون من 10 أرقام",
      applicationtype:"نوع الطلب",
        IqamaIDstartswith2:"يبدأ رقم الإقامة بالرقم 2",
        fCerNo: "رقم الشهادة",
        fCerType: "نوع الشهادة",
        continue: 'متابعة',
        gccIDError:"رقم هوية الخليجيين يجب ان تكون من 7 الى 15 رقم",
        fTaxPer: "سنة الإقرار",
        tin: 'الرقم المميز' ,
        VATAccNo: 'رقم حساب ضريبة القيمة المضافة',
        idNo: 'رقم الهوية',
        status: "الحالة",
        taxpayerName: 'اسم المكلف',
        address: 'العنوان',
        iDType: 'نوع الهوية',
        contactPersonName : 'اسم جهة الاتصال',
        typeoFsecuritySubmitted: 'نوع الضمان المقدم',
        cashRefNo: 'الرقم المرجعي للحالة',
        securityAmount: 'مبلغ الضمان',
        submissionDate: 'تاريخ التقديم',
        preferredAccount: 'الحساب المفضل',
        preferredRefundMethond: 'طريقة الاسترداد المفضلة',
        requestsent: 'تم ارسال الطلب',
        successPageSubHeading: 'تم استلام طلب الإفراج عن الضمانات بنجاح',
        name: 'الاسم',
        requestNumber: 'رقم الطلب',
        gotoDashboard: 'الانتقال الى الشاشة الرئيسية',
        date: 'التاريخ',
        downloadConfirmation: 'تحميل التأكيد',
        pleaseselectthetypeofsecuritysubmitted: 'يرجى تحديد نوع الضمان المقدم',
        mainoutlitCRLicence:'السجل التجاري او الرخصة للفرع الرئيسي',
        mainoutlit:'اسم السجل التجاري او الرخصة للفرع الرئيسي',
        cRLicense:'رقم السجل التجاري او الرخصة للفرع الرئيسي',
        cashsecurity:"دفعات عن طريق سداد",
        bankguarantee:"ضمان بنكي",
        Pleaseselectthecasereferencenumber:'يرجى اختيار الرقم المرجعي للحالة التي قدم لها الضمان',
        caseReferenceNumber:"الرقم المرجعي للحالة",
        SecurityAmount:'مبلغ الضمان',
        Submissiondatestring:'تاريخ التقديم',
        Pleasespecifyyourpreferredrefundmethod:"يرجى اختيار طريقة الاسترداد المفضلة",
        Cashrefund :'الاسترداد النقدي (عبر الحساب البنكي)',
        CarryforwardofcreditinVATaccount:"ترحيل الرصيد الدائن لحساب ضريبة القيمة المضافة",
        Selectthepreferredaccount:"يرجى اختيار رقم الآيبان الصحيح من اللائحة المتاحة",
        addNewRequest:'طلب جديد',
        search:"بحث",
        continueText :'متابعة',
        confirm:"تأكيد",
        edit:"تعديل",
        idMsg: " الرجاء ادخال رقم الهوية",
        dobMsg: " الرجاء ادخال تاريخ الميلاد",
        textArea: "تم تجاوز عدد الأحرف المسموح به. لا يمكن إضافة المزيد من النص",
        gccError: "رقم هوية الخليجيين يجب ان تكون من 7 الى 15 رقم",
        pleasecorrectthehighlightedfields:"الرجاء إكمال الحقول المحددة كما هو موضح للمتابعة",
        creationdate:'تاريخ الطلب',
        filter:'فلتر',
        apply:'تقديم',
        modal: {
          dob: "تاريخ الميلاد",
          validate: "التحقق",
          close: "إغلاق",

      },
      instructionDialogue: {
        title: "التعليمات والشروط",
        p1: "يرجى تعبئة المعلومات المطلوبة لكل خطوة، ولا يمكن تقديم الطلب بنجاح حتى يتم الانتهاء من جميع الحقول الإلزامية يجب على مقدم الطلب التأكد من أن لديه المرجع أو رقم الطلب المتعلق بالقرار الذي يرغب في مراجعته",
        p2: "يرجى الرجوع إلى قسم الأسئلة الشائعة قبل تعبئة استمارة الطلب",
        close: "إغلاق",
        checkboxText:"أوافق على هذه التعليمات والشروط والانتقال الى الخطوة التالية",
        buttonText:'الإفراج عن الضمانات',
    
    },


    f3: {
      title: "التعهد",
      label1: "نوع الهوية",
      label2: "رقم الهوية",
      label3: "اسم جهة الاتصال",
      term: "أتعهد بأن جميع المعلومات المذكورة في الأعلى حقيقية وصحيحة على حد علمي",
      id1: "الهوية الوطنية",
      id2: "رقم الإقامة",
      id3: "هوية مواطني دول الخليج"
  },
        menu: [
          {
            //  title: "Taxpayer Details",
            title: 'الإفراج عن الضمانات',
            //subtitle: "Complete the below details",
            //step: "assets/image/1-st.svg",
          },
          {
            title: "تفاصيل المكلف",
            subtitle: 'الرجاء اكمال البيانات التالية',
            step: "assets/image/1-st.svg",
            //step: "assets/image/2-nd.svg",
            
          },
          {
            title: 'تفاصيل الضمان',
            subtitle: 'الرجاء اكمال البيانات التالية',
            step: "assets/image/2-nd.svg",
            //step: "assets/image/3-rd.svg",
          },
          //Declaration
          {
              title: "التعهد",
              subtitle: "أقر بموجب هذا بأنني مفوض لملء هذا النموذج للشخص الخاضع للضريبة وأن جميع المعلومات الواردة صحيحة",
              step: "assets/image/3-rd.svg",
             // step: "assets/image/4-th.svg",
            },
          {
            title: "ملخص",
            subtitle: "مراجعة البيانات التالية",
           step: "assets/image/4-th.svg",
           // step: "assets/image/4-th.svg",
          },
    
        ],
    
  
      },
  };


export const ApiConstantsReleaseSecurity = {
  getInitialListData: "sap/opu/odata/SAP/ZDP_ITAP_SRV",
  getInitialData: "sap/opu/odata/SAP/ZDP_TPEV_M_SRV",
  Attachment: "sap/opu/odata/SAP/ZDP_INDTAX_ATT_SRV",
  UserTypeValidation: "sap/opu/odata/SAP/Z_REG_GET_TAXPAYER_SRV/",

}