export const RequestForContractRelease = {
  langz: {
    eng: {
      dir: "ltr",
      menu: [
        {
          title: "Contract Release Applications",
          subtitle: "Complete below details",
          step: "assets/image/1-st-ctr.svg",
        },
        {
          title: "Request For Review",
          subtitle: "Complete the below details",
          step: "assets/image/2-nd-ctr.svg",
        },
        {
          title: "Description & Attachments",
          subtitle:
            "Please state the decision you would like to review and the grounds for your request & provide us with supporting documents to support your reasons for a review.",
          step: "assets/image/3-rd-ctr.svg",
        },
        {
          title: "Review Details",
          subtitle: "Complete the following details",
          step: "assets/image/4-th-ctr.svg",
        },
        {
          title: "Security Payments",
          subtitle: "Complete the following details",
          step: "assets/image/5-th-ctr.svg",
        },
      ],
      screen1: {
        hamb1: "Tax Management",
        hamb2: "Zakat Services",
        hamb3: "Contract Release Applications",
        title1: "Contract Release Applications",
        search: "Search",
        title2: "New Application Request",
        requestTitle: "Application Requests",
        back: "Back",
        SAR: "SAR",
        edit: "Edit",
        confirm: "Confirm",
        mbMax: "10MB Max",
        filesizeMessage: "File size should not be more than 10 MB.",
        invalidFormat: "Upload files with allowed extensions only",
        fileAlreayExists: "File with the same name already exists",
        Submitted: "Submitted",
        Pending: "Pending",
        Rejected: "Rejected",
        status: "Status",
        monthly: "monthly",
      },

      screen2: {
        title: "Instructions",
        p1:
          "Please read instructions and guidance before filling this Excise Tax Transational Declaration return, if you have any questions please call 19993 or visit",
        p4: " https://www.gazt.gov.sa",
        p2:
          "1. Must attached a copy of the contract requred to release and amounts which distursed depend on the release letter. The contract should be in Arabic and in the case of the contract in English, must submit Translated Arabic version approved by certified translation Office.",
        p5: " ",
        p3:
          "2. Must attached a copy of invoices and purchase orders required the release of their amount values.",
        checkbox: "I agree with these conditions.",
        button: "Request New Certificate",
      },
      screen3: {
        hamb1: "Tax Management",
        hamb2: "Zakat Services",
        hamb3: "Contract Release Applications",
        hamb4: "New Contract Release Application",
        title: "Release Details",
        subtitle: "Complete the details below",
        name: "Name on Contract",
        number: "Contract Number",
        type: "Contract Type",
        period: "Submitted Date",
        amount_total: "Total Amount of Contract (A number)",
        amount_requested: "Amount required to Release",
        table_h1: "Current Assets",
        table_h2: "Percentage",
        table_h3: "Amount (SAR)",
        tr1: "Profit Estimated for Contract",
        tr2: "Estimated Profit for Zakat",
        tr3: "Estimated Profit for Tax",
        tr4: "The Value of Tax dues",
        tr5: "The Value of Zakat dues",
        total: "Total Dues",
        continue: "Continue",
        nameData: "Name",
        from: "From",
        to: "To",
      },
      screen4: {
        hamb1: "Tax Management ",
        hamb2: "Zakat Services",
        hamb3: "Contract Release Applications",
        hamb4: "New Contract Release Application",
        title: "Attachments",
        subtitle: "Complete the details below",
        caption:
          "Attach a copy of the contract required to release and amounts which disbursed depend on the release letter. The contract should be in Arabic and in the case of the contract in English, must submit translated Arabic version approved by certified translation Office.",
        caption2:
          "Attach a copy of invoices and purchase orders required the release of their amount values",
        t13: "(Choose only file with extension Doc,Docx,Jpg,PDF,xls,xlsx)",

        card_title: "Drag and drop file to upload documentation",
        card_subtitle: "50MB max",
        continue: "Continue",
      },
      screen5: {
        title: "Remarks & Description",
        subtitle: "Complete the details below",
        remarks: "Remarks",
        desc: "Detail Description",
        continue: "Continue",
      },
      screen6: {
        title: "Declaration",
        subtitle:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        name: "Full Name",
        designation: "Designation",
      },
      screen7: {
        title: "Summary",
        subtitle: "Review the information below",
        card1_title: "Release Details",
        name: "Name on Contract",
        number: "Contract Number",
        type: "Contract Type",
        period: "Contract Period",
        amount_required: "Amount required to Release",
        amount_total: "Total Amount of Contract (A number)",
        total_dues: "Total Dues",
        file_Title: "Attachments",
        file1: "Attach Contract",
        file2: "Attach Invoice Copy",
        remarks_Title: "Remarks",
        remarks: "Remarks",
        desc: "Detail Description",
        declaration_title: "Declaration",
        declaration_name: "Full Name",
        designation: "Designation",
        terms:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        confirm: "Confirm",
      },
      screen8: {
        title: "Contract Release",
        subtitle: "Your Contract is successfully released",
        number: "Request Number",
        button: "Download Acknowledgement",
        link: "Download Form",
        redirect: "Go to Dashboard",
      },
      filterModal: {
        title: "Filter",
        label1: "Form Type",
        label2: "Status",
        btnTitle: "Apply",
      },
      RFCRErrors: {
        AContNmMsg: "Please enter TP Name",
        AContNoMsg: "Please enter contract number",
        AtypeMsg: "Contracting Type cannot be Blank",
        AContDtMsg: "Please enter valid contract start date",
        AContEndMsg: "Please Enter Valid Contract End Date",
        ATotalAmtMsg: "Please enter the total contract amount",
        AReqAmtMsg: "Please Enter Valid Amount Required to Release",
        AReqAmt2Msg: "Required Amount Should not be greater than Total Amount",
        AContDt2Msg: "Contract Date Should not be greater Current Date",
        AContEndD2tMsg:
          "Contract End Date Should not be less from Contract Date",
        FullNameMsg: "Please Enter Full Name",
        DesMsg: "Please Enter Designation",
        attachMsg: "Please Attach Mandatory Attachments.",
        e3: "Tin is Required.",
      },
      TooltipConstants: {
        proftForContract:
          "Multiply released amount with Estimated profit for contract",
        proftForZakat:
          "Multiply Estimated profit for contract with Saudi share %",
        proftForTax:
          "Multiply Estimated profit for contract with Non-Saudi share%",
        valueTaxDues: "Multiply Estimated profit for TAX with 20 %",
        valueZakatDues: "Multiply Estimated profit for ZAKAT with 2.5 %",
      },
      contractType: {
        ContType: [
          {
            Key: "",
            Text: "",
            Pert: "0.00",
          },
          {
            Key: "1",
            Text: "Supply for Aramco",
            Pert: "3",
          },
          {
            Key: "2",
            Text: "Supply and maintenance",
            Pert: "10.50",
          },
          {
            Key: "3",
            Text: "supply, maintenance and operating",
            Pert: "10.50",
          },
          {
            Key: "4",
            Text: "Disassemble, installation and operate",
            Pert: "10.50",
          },
          {
            Key: "5",
            Text: "supply, installation and operate",
            Pert: "10.50",
          },
          {
            Key: "6",
            Text: "Disassemble, installation and transport",
            Pert: "10.50",
          },
          {
            Key: "7",
            Text: "Cleanliness and maintenance",
            Pert: "10.50",
          },
          {
            Key: "8",
            Text: "Supply, installation and deliver",
            Pert: "10.50",
          },
          {
            Key: "9",
            Text: "maintenance and operate",
            Pert: "10.50",
          },
          {
            Key: "10",
            Text: "transport",
            Pert: "10.50",
          },
          {
            Key: "11",
            Text: "supply and water transport",
            Pert: "10.50",
          },
          {
            Key: "12",
            Text: "construction",
            Pert: "10.50",
          },
          {
            Key: "13",
            Text: "maintenance",
            Pert: "10.50",
          },
          {
            Key: "14",
            Text: "operate",
            Pert: "10.50",
          },
          {
            Key: "15",
            Text: "Design and construction",
            Pert: "10.50",
          },
          {
            Key: "16",
            Text: "supply and design",
            Pert: "10.50",
          },
          {
            Key: "17",
            Text: "supply and oprate",
            Pert: "10.50",
          },
          {
            Key: "18",
            Text: "supply and installation",
            Pert: "10.50",
          },
          {
            Key: "19",
            Text: "design, supply and installation",
            Pert: "10.50",
          },
          {
            Key: "20",
            Text: "design, supply and oprate (maintenance)",
            Pert: "10.50",
          },
          {
            Key: "21",
            Text: " equipment rental",
            Pert: "10.50",
          },
          {
            Key: "22",
            Text: "maintenance, cleanliness and oprate",
            Pert: "10.50",
          },
          {
            Key: "23",
            Text: "cleanliness",
            Pert: "10.50",
          },
          {
            Key: "24",
            Text: "catering",
            Pert: "10.50",
          },
          {
            Key: "25",
            Text: "Security guards",
            Pert: "10.50",
          },
          {
            Key: "26",
            Text: "Roads maintenance",
            Pert: "10.50",
          },
          {
            Key: "27",
            Text: "Labor recruiting",
            Pert: "10.50",
          },
          {
            Key: "28",
            Text: "Contracting Roads and Transport",
            Pert: "10.50",
          },
          {
            Key: "29",
            Text: "Supply",
            Pert: "15",
          },
          {
            Key: "30",
            Text: "Supply and delivery to warehouses",
            Pert: "15",
          },
          {
            Key: "31",
            Text: "Supply and delivery port",
            Pert: "15",
          },
          {
            Key: "32",
            Text: "Operation of services at the port",
            Pert: "15",
          },
          {
            Key: "34",
            Text: "Consultations",
            Pert: "20",
          },
          {
            Key: "35",
            Text: "Design and consulting",
            Pert: "20",
          },
          {
            Key: "36",
            Text: "Private Consultante",
            Pert: "20",
          },
          {
            Key: "37",
            Text: "Studies and Consulting",
            Pert: "20",
          },
          {
            Key: "33",
            Text: "Other",
            Pert: "15",
          },
        ],
      },
    },

    arb: {
      dir: "rtl",
      menu: [
        {
          title: "طلبات الإفراج عن العقود‎",
          subtitle: "أكمل البيانات التالية",
          step: "assets/image/1-st-ctr.svg",
        },
        {
          title: "Request For Review",
          subtitle: "أكمل البيانات التالية",
          step: "assets/image/2-nd-ctr.svg",
        },
        {
          title: "Description & Attachments",
          subtitle:
            "Please state the decision you would like to review and the grounds for your request & provide us with supporting documents to support your reasons for a review.",
          step: "assets/image/3-rd-ctr.svg",
        },
        {
          title: "Review Details",
          subtitle: "Complete the following details",
          step: "assets/image/4-th-ctr.svg",
        },
        {
          title: "Security Payments",
          subtitle: "Complete the following details",
          step: "assets/image/5-th-ctr.svg",
        },
        {
          title: "Declaration",
          subtitle:
            "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
          step: "assets/image/76.svg",
        },
        {
          title: "Summary",
          subtitle: "Review the below information",
          step: "assets/image/77.svg",
        },
      ],
      screen1: {
        hamb1: "إدارة الضرائب",
        hamb2: "خدمات الزكاة",
        hamb3: "طلبات الإفراج عن العقود‎",
        title1: "طلبات الإفراج عن العقود‎",
        search: " بحث",
        title2: "طلب الإفراج عن عقد",
        requestTitle: "الطلبات",
        SAR: "ريال سعودي",
        back: "رجوع",
        edit: "تعديل",
        confirm: "تأكيد",
        mbMax: "10MB الحد الأعلى",
        filesizeMessage: "يجب أن يكون حجم الملف أقل من 10 ميجا بايت.",
        invalidFormat: "الرجاء استخدام صيغ الملفات المسموح بها فقط",
        fileAlreayExists: "يوجد ملف بنفس الاسم مرفق مسبقا",
        Submitted: "مقدمة",
        Pending: "معلق",
        Rejected: "مرفوض",
        status: "الحالة",
        monthly: "شهري",
      },
      screen2: {
        title: "التعليمات",
        p1:
          "يرجى قراءة التعليمات والإرشادات قبل تقديم إقرار الضريبة الانتقائية ، إذا كان لديك أي أسئلة ، يرجى الاتصال 19993 أو زيارة",
        p4: " https://www.gazt.gov.sa",
        p5: "",

        p2:
          "1. الرجاء إرفاق صورة العقد المطلوب الإفراج عنه باللغة العربية أو مترجم من جهة معتمدة",

        p3: "2. صورة من الفواتير وأوامر الشراء المطلوب الإفراج عن قيمتها",
        checkbox: "أوافق على هذه الشروط",
        button: "طلب شهادة ",
      },
      screen3: {
        hamb1: "إدارة الضرائب",
        hamb2: "خدمات الزكاة",
        hamb3: "طلبات الإفراج عن العقود‎",
        hamb4: "طلب الإفراج عن عقد",
        title: "تفاصيل الإفراج‎",
        subtitle: "أكمل البيانات التالية",
        name: "اسم العقد",
        number: "رقم العقد",
        type: "النوع (عقد/امر شراء/فاتورة)",
        period: "تاريخ التقديم",
        amount_total: "القيمة الإجمالية للعقد(رقماً)‎",
        amount_requested: "المبلغ المطلوب الإفراج عن عنه",
        table_h1: "الأصول المتداولة",
        table_h2: "النسبة",
        table_h3: "المبلغ",
        tr1: "الربح التقديري للعقد",
        tr2: "الربح التقديري الخاضع للزكاة",
        tr3: "الربح التقديري الخاضع للضريبة",
        tr4: "قيمة الضريبة المستحقة",
        tr5: "قيمة الزكاة المستحقة",
        total: "إجمالي المستحق",
        continue: "متابعة‎",
        nameData: "الاسم",
        from: "من",
        to: "إلى",
      },
      screen4: {
        hamb1: "إدارة الضرائب",
        hamb2: "خدمات الزكاة",
        hamb3: "طلبات الإفراج عن العقود‎",
        hamb4: "طلب الإفراج عن عقد",
        title: "المرفقات",
        subtitle: "أكمل البيانات التالية",
        caption:
          "الرجاء إرفاق صورة العقد المطلوب الإفراج عنه باللغة العربية أو مترجم من جهة معتمدة",
        caption2: "(صورة من الفواتير وأوامر الشراء المطلوب الإفراج عن قيمتها)",
        t13: "Doc , Docx, jpg , PDF , xls, xlsx الرجاء إختيار فقط الملفات بصيغة",

        card_title: "سحب وإفلات الملف لتحميل الوثيقة",
        card_subtitle: "50MB max",
        continue: "متابعة‎",
      },
      screen5: {
        title: "الملاحظات و الوصف",
        subtitle: "أكمل البيانات التالية",
        remarks: "ملاحظات",
        desc: "تفاصيل الوصف",
        continue: "متابعة‎",
      },
      screen6: {
        title: "التعهد",
        subtitle:
          "أقر بموجب هذا بأنني مفوض لملء هذا النموذج للشخص الخاضع للضريبة وأن جميع المعلومات الواردة صحيحة",
        name: "الاسم الكامل",
        designation: "الصفة",
      },
      screen7: {
        title: "ملخص",
        subtitle: "مراجعة البيانات التالية",
        card1_title: "تفاصيل الإفراج‎",
        name: "اسم العقد",
        number: "رقم العقد",
        type: "النوع (عقد/امر شراء/فاتورة)",
        period: "تاريخ العقد",
        amount_required: "المبلغ المطلوب الافراج عنه",
        amount_total: "القيمة الإجمالية للعقد(رقماً)‎",
        total_dues: "إجمالي المستحق",
        file_Title: "المرفقات",
        file1: "إرفاق العقد",
        file2: "إرفاق صورة الفاتورة",
        remarks_Title: "ملاحظات",
        remarks: "ملاحظات",
        desc: "تفاصيل الوصف",
        declaration_title: "التعهد",
        declaration_name: "الاسم الكامل",
        designation: "الصفة",
        terms:
          "أقر بموجب هذا أنني مفوض لاستكمال هذا النموذج للشخص الخاضع للضريبة وأن جميع المعلومات الواردة صحيحة.",

        confirm: "تأكيد",
      },
      screen8: {
        title: "الإفراج عن عقد",
        subtitle: "تم استلام طلب الإفراج عن العقد بنجاح",
        number: "رقم الطلب",
        button: "تحميل اشعار الاستلام",
        link: "تحميل النموذج",
        redirect: "الانتقال الى الشاشة الرئيسية",
      },
      filterModal: {
        title: "فلتر",
        label1: "نوع النموذج",
        label2: "الحالة",
        btnTitle: "تقديم",
      },
      contractType: {
        ContType: [
          {
            Key: "",
            Text: "",
            Pert: "0.00",
          },
          {
            Key: "1",
            Text: "توريد لشركة ارامكو السعودية",
            Pert: "3",
          },
          {
            Key: "2",
            Text: "توريد وصيانة",
            Pert: "10.50",
          },
          {
            Key: "3",
            Text: "توريد وتركيب وتشغيل",
            Pert: "10.50",
          },
          // {
          //   Key: "4",
          //   Text: "توريد وصيانة",
          //   Pert: "10.50",
          // },
          {
            Key: "5",
            Text: "توريد وصيانة وتشغيل",
            Pert: "10.50",
          },
          {
            Key: "6",
            Text: "فك وتركيب وتشغيل",
            Pert: "10.50",
          },
          {
            Key: "7",
            Text: "نظافة وصيانة",
            Pert: "10.50",
          },
          {
            Key: "8",
            Text: "توريد وتركيب وتسليم",
            Pert: "10.50",
          },
          {
            Key: "9",
            Text: "صيانة وتشغيل",
            Pert: "10.50",
          },
          {
            Key: "10",
            Text: "نقل",
            Pert: "10.50",
          },
          {
            Key: "11",
            Text: "توريد ونقل مياه",
            Pert: "10.50",
          },
          {
            Key: "12",
            Text: "إنشاء ومقاولات",
            Pert: "10.50",
          },
          {
            Key: "13",
            Text: "صيانة",
            Pert: "10.50",
          },
          {
            Key: "14",
            Text: "تشغيل",
            Pert: "10.50",
          },
          {
            Key: "15",
            Text: "تصميم وإنشاء",
            Pert: "10.50",
          },
          {
            Key: "16",
            Text: "توريد وتصميم",
            Pert: "10.50",
          },
          {
            Key: "17",
            Text: "توريد وتشغيل",
            Pert: "10.50",
          },
          {
            Key: "18",
            Text: "توريد وتركيب",
            Pert: "10.50",
          },
          {
            Key: "19",
            Text: "تصميم وتوريد وتركيب",
            Pert: "10.50",
          },
          {
            Key: "20",
            Text: "تصميم توريد وتشغيل (صيانة)",
            Pert: "10.50",
          },
          {
            Key: "21",
            Text: "تأجير معدات",
            Pert: "10.50",
          },
          {
            Key: "22",
            Text: "صيانة ونظافة وتشغيل",
            Pert: "10.50",
          },
          {
            Key: "23",
            Text: "نظافة",
            Pert: "10.50",
          },
          {
            Key: "24",
            Text: "تأمين الاعاشة",
            Pert: "10.50",
          },
          {
            Key: "25",
            Text: "حراسات أمنية",
            Pert: "10.50",
          },
          {
            Key: "26",
            Text: "صيانة طرق",
            Pert: "10.50",
          },
          {
            Key: "27",
            Text: "تأمين عمالة",
            Pert: "10.50",
          },
          {
            Key: "28",
            Text: "مقاولات طرق ومواصلات",
            Pert: "10.50",
          },
          {
            Key: "29",
            Text: "توريد",
            Pert: "15",
          },
          {
            Key: "30",
            Text: "توريد وتسليم للمستودعات",
            Pert: "15",
          },
          {
            Key: "31",
            Text: "توريد وتسليم الميناء",
            Pert: "15",
          },
          {
            Key: "32",
            Text: "خدمات تشغيل في الميناء",
            Pert: "15",
          },
          {
            Key: "34",
            Text: "استشارات",
            Pert: "20",
          },
          {
            Key: "35",
            Text: "تصميم واستشارة",
            Pert: "20",
          },
          {
            Key: "36",
            Text: "مستشار خاص",
            Pert: "20",
          },
          {
            Key: "37",
            Text: "الدراسات واستشارات",
            Pert: "20",
          },
          {
            Key: "33",
            Text: "اخرى",
            Pert: "15",
          },
        ],
      },
      RFCRErrors: {
        AContNmMsg: "الرجاء إدخال اسم المكلف",
        AContNoMsg: "الرجاء إدخال رقم العقد",
        AtypeMsg: "الرجاء تحديد نوع العقد",
        AContDtMsg: "الرجاء إدخال تاريخ بداية العقد بشكل صحيح",
        AContEndMsg: "الرجاء إدخال تاريخ نهاية العقد بشكل صحيح",
        ATotalAmtMsg: "الرجاء إدخال إجمالي مبلغ العقد",
        AReqAmt2Msg: "المبلغ المطلوب يجب أن لا يزيد عن المبلغ الإجمالي",
        AReqAmtMsg: "الرجاء إدخال المبلغ المطلوب الإفراج عنه",
        AContDt2Msg: "تاريخ العقد لا يمكن ان يكون اكبر من التاريخ الحالي",
        MaxEndDate: "تاريخ نهاية العقد يجب ان يكون اقل التاريخ الحالي",
        AContEndD2tMsg: "تاريخ نهاية العقد يجب ان لا يكون اقل تاريخ التعاقد",
        FullNameMsg: "الرجاء إدخال الاسم كاملا",
        DesMsg: "الرجاء إدخال المسمى الوظيفي",
        attachMsg: "الرجاء رفع الملفات المطلوبة",
        e3: "القصدير مطلوب.",
      },
      TooltipConstants: {
        proftForContract:
          'حاصل ضرب "المبلغ المطلوب الإفراج عنه" مع "نسبة الربح التقديرية للعقد"',
        proftForZakat:
          'حاصل ضرب "الربح التقديري للعقد" مع "حصة الشريك السعودي %"',
        proftForTax:
          'حاصل ضرب "الربح التقديري للعقد" مع "حصة الشريك الغير السعودي %"',
        valueTaxDues: 'حاصل ضرب "الربح التقديري الخاضع للضريبة" في "20 %"',
        valueZakatDues: 'حاصل ضرب "الربح التقديري الخاضع للزكاة" في "2.5 %"',
      },
    },
  },
};
export const RFCRAPIConstants = {
  RFCREncryptDetails: "sap/opu/odata/SAP/ZDP_EP_USER_ANG_SRV/EP_USERSet",
  RFCRCreateNewApp: "sap/opu/odata/SAP/Z_TP_NOTES_TP11_SRV/znotes_tp11Set",
  RFCRDashboard: "sap/opu/odata/SAP/ZDP_TP_DASHBOARD_SRV/HeaderSet",
  RFCROpenAppl: "sap/opu/odata/SAP/ZDP_ITAP_SRV/TPFILLSet",
  RFCROpenApp2: "sap/opu/odata/SAP/Z_TP_NOTES_TP11_SRV/znotes_tp11Set",
  RFCRPost: "sap/opu/odata/SAP/Z_TP_NOTES_TP11_SRV/znotes_tp11Set",
  RFCRGetConfirm: "sap/opu/odata/SAP/Z_GET_ACK_LETTER_SRV/Ack_letterSet",
  RFCRDownload: "sap/opu/odata/SAP/Z_GET_COVER_FORM_SRV/cover_formSet",
  RFCRTaxPayerDashboard: "sap/opu/odata/SAP/ZTAXPAYERDBNEW_SRV/HeaderSet",
  RFCRFileUpload: "sap/opu/odata/SAP/Z_SAVE_ATTACH_SRV/AttachSet",
  RFCRFileDelete: "sap/opu/odata/SAP/Z_SAVE_ATTACH_SRV/AttachMedSet",
};
