export const requestCertificateConstants = {
    eng: {
      dir: "ltr",
      downloadForm:"Download Form",
      zeroKbFileError: "Unable to load attachments.",
      drag: "Drag and drop file to upload documentation",
      bc1: "Tax Management",
      bc2: "Zakat Services",
      bc3: "Zakat Certificates",
      bc4: "Zakat Certificate Request",
      back: "Back",
      mbMax: "Attachment(Only One Allowed - Maximum Size 10 MB)",
      fCerNo: "Certificate Number",
      fCerType: "Certificate Type",
      continue: "Continue",
      confirm:"Confirm",
      fTaxPer: "Tax Year",
      applicationtype:"Application type",
      addReqText:"Request Zakat Tax Certificate",
      zakatTaxCertificate:'Zakat Tax Certificate',
      search:"Search",
      instructionTitle:"Instructions",
      instructionLine1:"1. Attach a request letter displaying the with a reason for this request",
      instructionLine2:"For Arabic line2",
      instructionLine3:"For Arabic line3",
      instructionLine4:"For Arabic line4",
      instructionCheckboxText:"I Agree", 
      downloadConfirmation:"Download Confirmation",
      referenceNumber:"Reference Number",
      yourZakatCertificateRequestsuccessfullysubmitted:"Your Zakat Certificate Request is successfully submitted",
      zakatCertificateRequest:"Zakat Certificate Request",
      uploadFileWithAllowedExtensionOnly : "Upload files with allowed extensions only",
      fileWithSameNameExits:"File with the same name already exists",
      filesizeshouldbelessthanXMB: "File size should be less than 10 MB",
      maximumnoofallowedattachments:"Maximum no. of allowed attachments is 1.",
      somethingWentWrong:"Something went wrong",
      fileNameLarge: 'File name must not exceed 100 characters',
      status: 'Status',
      date:'Date',
      fbNumber:'Fb Number',
      errCerType: "Certificate Type cannot be Blank",
      errTaxYear: "Tax Year cannot be Blank",
      ValidTaxType: "Please Select Valid Tax Year",
      ValidCerType: "Please Select Valid Certificate Type",
      CertificateDetails: 'Certificate Details',
      edit:'Edit',
      attachments:'Attachments',
      attachRequestLetter:"Attach Request Letter",
      downloadAck:"Download Acknowledgement",


      menu: [
        {
          title: "Zakat",
          // subtitle: "Complete the below details",
          step: "assets/image/1-st.svg",
        },
        {
          title: "Certificate Details",
          subtitle: "Complete the below details",
          step: "assets/image/3steps-1.svg",
        },
        {
          title: "Attachments",
          subtitle: "Select the type of document",
          step: "assets/image/3steps-2.svg",
        },
        {
          title: "Summary",
          subtitle: "Review the information below",
          step: "assets/image/3steps-3.svg",
        },
  
      ],
  

    },
    arb: {
      dir: "rtl",
      mbMax: "المرفق ( ارفاق ملف واحد فقط – الحجم الاقصى للملف 10 ميجا)",
      zeroKbFileError: "تعذر تحميل المرفقات.",
      drag: "سحب وإفلات الملف لتحميل الوثيقة",
      zakatTaxCertificate:'شهادة الزكاة',
      downloadForm:"تحميل النموذج ",
      bc1: "إدارة الضريبة",
      bc2: "خدمات الزكاة",
      bc3: "شهادات الزكاة",
      bc4: "طلب شهادة الزكاة",
      back: "رجوع",
      continue: 'متابعة',
      fCerNo: "رقم الشهادة",
      fCerType: "نوع الشهادة",
      fTaxPer: "سنة الإقرار",
      addReqText:"طلب شهادة الزكاة",
      search:"بحث",
      fileNameLarge: 'يجب ألا يزيد طول اسم الملف عن 100',
      instructionTitle:"التعليمات",
      instructionLine1:"تهدف الخدمة الى السماح للمنشأة المسجلة بطلب الحصول على شهادة الزكاة / الضريبة وفق الخطوات التالية:",
      instructionLine2:"1 - تقديم الإقرار للفترة المالية.",
      instructionLine3:"2 - سداد مبلغ الزكاة / الضريبة المستحق.",
      instructionLine4:"3 - تقديم طلب الحصول على الشهادة.",
      instructionCheckboxText:"موافق",
      downloadConfirmation:"تحميل التأكيد",
      referenceNumber:"الرقم المرجعي",
      yourZakatCertificateRequestsuccessfullysubmitted:"تم استلام طلب شهادة الزكاة بنجاح",
      zakatCertificateRequest:"طلب شهادة الزكاة",
      uploadFileWithAllowedExtensionOnly : "الرجاء استخدام صيغ الملفات المسموح بها فقط",
      fileWithSameNameExits:"يوجد ملف بنفس الاسم مرفق مسبقا",
      filesizeshouldbelessthanXMB: "يجب ان يكون حجم الملف اقل من 10 ميقا",
      maximumnoofallowedattachments:"يجب أن لا يزيد عدد المرفقات عن 1 ملفات.",
      somethingWentWrong:"حدث شئ خطأ",
      confirm: "تأكيد",
      status: "الحالة",
      date:'بيانات المنشأة',
      fbNumber:'الرقم المرجعي للنموذج',
      errCerType: "نوع الشهادة يجب أن لا يكون فارغ",
      errTaxYear: "سنة الإقرار يجب أن لا تكون فارغة",
      ValidCerType: "الرجاء اختيار نوع الشهادة المطلوبه",
      ValidTaxType: "الرجاء اختيار سنة الإقرار",
      CertificateDetails: 'تفاصيل الشهادة',
      edit: "تعديل",
      attachments:"مرفقات",
      attachRequestLetter:"إرفاق رسالة الطلب",
      applicationtype:"نوع الطلب",
      downloadAck:"تحميل اشعار استلام",


      menu: [
        {
          title: "الزكاة",
          // subtitle: "Complete the below details",
          step: "assets/image/1-st.svg",
        },
        {
          title: "تفاصيل الشهادة",
          subtitle: "أكمل البيانات التالية",
          step: "assets/image/2-nd.svg",
        },
        {
          title: "مرفقات",
          subtitle: "اختر نوع الملف",
          step: "assets/image/3-rd.svg",
        },
        {
          title:  "ملخص",
          subtitle: "مراجعة البيانات التالية",
          step: "assets/image/4-th.svg",
        },

  
      ],
  
    
    }
  };