export const userManagementConstants = {

  eng: {
    dir: 'ltr',
    userManagement: "User Management",
    back: 'Back',
    allUsers: "All Users",
    activeUsers: "Active Users",
    inactiveUsers: "Inactive Users",
    profile: "Profile",
    management: "Management",
    branch: "Branch",
    active: "Active",
    allocatedService: "Allocated Service",
    instalmentPlan: "Allocated Service",
    addUser: "Add New User",
    activeTag: "Active",
    inActiveTag: "Inactive",
    taskAllocationh: "Task Allocation",
    activateUser: "Activate Member",
    deactivateUser: "Deactivate Member",
    userSuccessfullyCreate: "User successfully created",
    userSuccessfullyDeleted: "User Successfully Deactivated",
    userSuccessfullyActivated:  "User successfully Activated",
    deactivate:  "Deactivate",
    whtHappensWhenUserisDeactivated: "What happens when the user is deactivated?",
    modalBodyA:"The user will no longer be able to sign in nor to perfom the allocated tasks.",
    modalBodyB:"The user can be activated in the future from User Management area.",
    no:"No",
    name:"Name",
    status:"Status",
  },
arb: {
    dir: 'rtl',
    userManagement:  "إدارة المستخدمين  ",
    back: " رجوع",
    allUsers: "جميع المستخدمين",
    activeUsers: "المستخدمين النشطين",
    inactiveUsers: "المستخدمين غير النشطين",
    profile: "المستخدمون",
    management: "المستخدمون",
    branch: "الفرع",
    active: "نشط",
    allocatedService: "خدمة مخصصة",
    instalmentPlan: "طلب خطة تقسيط",
    addUser: "إضافة مستخدم جديد",
    activeTag: "نشط",
    inActiveTag: "غير نشط",
    taskAllocationh: "توزيع المهام",
    activateUser:"الأعضاء النشطين",
    deactivateUser: "إلغاء تنشيط العضو",
    userSuccessfullyCreate: "تم انشاء المستخدم بنجاح",
    userSuccessfullyDeleted: "تم إلغاء تنشيط المستخدم بنجاح",
    userSuccessfullyActivated:  "تم تفعيل المستخدم بنجاح",
    deactivate:  " إلغاء التنشيط ",
    whtHappensWhenUserisDeactivated: "ماذا يحدث عند إلغاء تنشيط المستخدم؟  ",
    modalBodyA:" لن يتمكن المستخدم من تسجيل الدخول او إتمام العمليات المسندة له ",
    modalBodyB:" يمكنك تنشيط المستخدم في المستقبل عن طريق خدمة إدارة المستخدمين ",
    no:"لا",
    name:" الاسم",
    status:"الحالة",
  }
};

export const ApiConstants = {
  getUserDetails: "sap/opu/odata/SAP/ZUSER_MGMT_SRV",
  getTaskAllocByTaxType: "sap/opu/odata/SAP/ZUSER_TASK_ALLOC_SRV",
  getDeletedUsers: "sap/opu/odata/SAP/ZUSER_MGMT_SRV",
  getUrlForFbgUid: "sap/opu/odata/SAP/ZDP_EP_USER_ANG_SRV",
  getUrlForFbgUid2: "sap/opu/odata/SAP/ZTAXPAYERDBNEW_SRV",
  validateIdAndDob: "sap/opu/odata/SAP/Z_REG_GET_TAXPAYER_SRV" 
}
