export const WithholdingObjectionConstants = {
  en: {
    dir: "ltr",
    bctitle1: "Objections & Reviews",
    bctitle2: "New Objection or Review",
    bctitle3: "New Withholding Objection",
    back: "Back",
    continue: "Continue",
    confirm: "Confirm",
    objection: "Objection Details",
    dragAndDrop: "Drag and drop file to upload documentation",
    revisedAmount: "Revised Amount",
    descriptionAndAttachment: "Description & Attachments",
    attachment: "Attachemnt",
    edit: "Edit",
    objectionAndWithdrawl: "Objection Withdrawal",
    escalationToAppealComitee: "Escalation to Appeal Comitee",
    withholdingObjectionDetails: "Withholding Objection Details",
    withholdingObjection: "Withholding Objection",
    approved: "Approved",
    process: [
      {
        title: "Taxpayer details",
        subtitle: "Complete below Details",
        step: "assets/image/steps-positive-7-1-st.svg",
      },
      {
        title: "Returns",
        subtitle: "Please select the Returns you want to object",
        step: "assets/image/steps-positive-7-2-nd.svg",
      },
      {
        title: "Objection Details",
        subtitle: "Complete below details",
        step: "assets/image/steps-positive-7-3-rd.svg",
      },
      {
        title: "Description & Attachments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/image/steps-positive-7-4-th.svg",
      },
      {
        title: "Authorized Representative",
        subtitle: "Complete this part only of you appoint a representative.",
        step: "assets/image/steps-positive-7-5-th.svg",
      },
      {
        title: "Declaration",
        subtitle:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        step: "assets/image/steps-positive-7-6-th.svg",
      },
      {
        title: "Summary",
        subtitle: "Review the below information",
        step: "assets/image/steps-positive-7-7-th.svg",
      },
    ],
    taxPayerForm: {
      details: "Taxpayer Details",
      tin: "TIN",
      name: "Taxpayer Name",
      license: "CR / License",
      outlet: "Main Outlet",
      address: "Address",
    },
    returns: {
      withholding: "Withholding Tax",
      amended: "Ammended by GAZT",
      year: "Assessment Year",
      assessmentAmount: "GAZT Assessment Amount",
    },
    objectionDetails: {
      withholdingReturn: "Withholding Tax Return",
      referenceNumber: "Reference Number",
      assessmentYear: "Assessment Year",
      period: "Period",
      currency: "Currency",
      assessmentAmount: "GAZT Assessment Amount",
      returnDetails: "Return Details",
      viewReturn: "View Return",
      disputeText:
        "The following data has been changed by GAZT. Please edit the data you want to dispute.",
      beginingOfPeriodBalance: 'Beginning of Period Balance',
      paidDuringYear: 'Paid During the Year',
      endOfPeriodBalance: 'End of Period Balance',
      paymentAmount: "Payment Amount",
        totalRevisedAmount: "Total Revisted Amount",
      disputedAmount: "Disputed Amount",
    },
    authorizedRepresentative: {
      title: "Authorized Representative",
      fullName: "Full Name",
      designation: "Designation",
      phoneNumber: "Phone Number",
      buildingName: "Building Name",
      fax: "Fax Number",
      levelAndStreetNumber: "Level & Street Number",
      email: "Email",
      city: "City",
    },
    declarationModule: {
      title: "Declaration",
      name: "Name of Applicant",
      position: "Position / Capacity",
      declaration:
        "I hereby declare that the above mentioned information is true and correct to the best of my knowledge and belief.",
    },
    successScreen: {
      objectionRequest: "Withholding Objection Request",
      successMessage:
        "We have received your Objection Application. Please retain this number for future reference and communication. GAZT will assess your Objection Application and in case of any missing information will revert back to you.",
      referenceNumber: "Reference Number",
      confirmation: "Download Confirmation",
      form: "Download Form",
    },
  },
  ar: {
    dir: "rtl",
    bctitle1: "Objections & Reviews",
    bctitle2: "New Objection or Review",
    bctitle3: "New Withholding Objection",
    back: "Back",
    continue: "Continue",
    confirm: "Confirm",
    objection: "Objection Details",
    dragAndDrop: "Drag and drop file to upload documentation",
    revisedAmount: "المبلغ الغير معترض عليه من المكلف",
    descriptionAndAttachment: "Description & Attachments",
    attachment: "المرفقات",
    edit: "Edit",
    objectionAndWithdrawl: "Objection Withdrawal",
    escalationToAppealComitee: "Escalation to Appeal Comitee",
    withholdingObjectionDetails: "Withholding Objection Details",
    withholdingObjection: "Withholding Objection",
    approved: "Approved",
    process: [
      {
        title: "Taxpayer details",
        subtitle: "Complete below Details",
        step: "assets/image/steps-positive-7-1-st.svg",
      },
      {
        title: "الاقرارات",
        subtitle: "Please select the Returns you want to object",
        step: "assets/image/steps-positive-7-2-nd.svg",
      },
      {
        title: "تفاصيل الاعتراض",
        subtitle: "Complete below details",
        step: "assets/image/steps-positive-7-3-rd.svg",
      },
      {
        title: "Description & Attachments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/image/steps-positive-7-4-th.svg",
      },
      {
        title: "الممثل الشرعي",
        subtitle: "Complete this part only of you appoint a representative.",
        step: "assets/image/steps-positive-7-5-th.svg",
      },
      {
        title: "Declaration",
        subtitle:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        step: "assets/image/steps-positive-7-6-th.svg",
      },
      {
        title: "Summary",
        subtitle: "Review the below information",
        step: "assets/image/steps-positive-7-7-th.svg",
      },
    ],
    taxPayerForm: {
      details: "Taxpayer Details",
      tin: "TIN",
      name: "Taxpayer Name",
      license: "CR / License",
      outlet: "Main Outlet",
      address: "Address",
    },
    returns: {
      withholding: "Withholding Tax",
      amended: "Ammended by GAZT",
      year: "سنة الربط",
      assessmentAmount: "GAZT Assessment Amount",
    },
    objectionDetails: {
      withholdingReturn: "Withholding Tax Return",
      referenceNumber: "Reference Number",
      assessmentYear: "Assessment Year",
      period: "Period",
      currency: "Currency",
      assessmentAmount: "GAZT Assessment Amount",
      returnDetails: "Return Details",
      viewReturn: "View Return",
      disputeText:
        "The following data has been changed by GAZT. Please edit the data you want to dispute.",
      beginingOfPeriodBalance: 'Beginning of Period Balance',
      paidDuringYear: 'Paid During the Year',
      endOfPeriodBalance: 'End of Period Balance',
      paymentAmount: "Payment Amount",
        totalRevisedAmount: "Total Revisted Amount",
      disputedAmount: "المبلغ المعترض عليه",
    },
    authorizedRepresentative: {
      title: "الممثل الشرعي",
      fullName: "الاسم الكامل",
      designation: "الصفة",
      phoneNumber: "Phone Number",
      buildingName: "اسم البناية",
      fax: "رقم الفاكس",
      levelAndStreetNumber: "الاقامة و اسم الشارع",
      email: "Email",
      city: "City",
    },
    declarationModule: {
      title: "Declaration",
      name: "Name of Applicant",
      position: "Position / Capacity",
      declaration:
        "I hereby declare that the above mentioned information is true and correct to the best of my knowledge and belief.",
    },
    successScreen: {
      objectionRequest: "Withholding Objection Request",
      successMessage:
        "We have received your Objection Application. Please retain this number for future reference and communication. GAZT will assess your Objection Application and in case of any missing information will revert back to you.",
      referenceNumber: "Reference Number",
      confirmation: "Download Confirmation",
      form: " تحميل النموذج",
    },
  },
};

export const ApiConstants = {
  getObjectionData: 'sap/opu/odata/SAP/Z_OBJ_ZNOB_SRV/ZNOB_HeaderSet'
}