export const ZakatObjectionConstants = {
  en: {
    dir: "ltr",
    bctitle1: "Objections & Reviews",
    bctitle2: "New Objection or Review",
    bctitle3: "New Zakat Objection",
    back: "Back",
    continue: "Continue",
    confirm: "Confirm",
    objection: "Objection Details",
    dragAndDrop: "Drag and drop file to upload documentation",
    revisedAmount: "Revised Amount",
    descriptionAndAttachment: "Description & Attachments",
    attachment: "Attachemnt",
    edit: "Edit",
    objectionAndWithdrawl: "Objection Withdrawal",
    escalationToAppealComitee: "Escalation to Appeal Comitee",
    zakatObjectionDetails: "Zakat Objection Details",
    zakatObjection: "Zakat Objection",
    approved: "Approved",
    sar: "SAR",
    addForm: "Add Form",
    max: "Max",
    filesizeMessage: "File size should not be more than 10 MB.",
    zeroFilesizeMessage: "Unable to load attachments",
    invalidFormat: "Upload files with allowed extensions only",
    fileAlreayExists: "File with the same name already exists",
    maxNoOfFiles: "Maximum no. of 10 attachments can be uploaded.",
    process: [
      {
        title: "Taxpayer details",
        subtitle: "Complete below Details",
        step: "assets/images/steps-positive-8-1-st.svg",
      },
      {
        title: "Objection Details",
        subtitle: "Complete below details",
        step: "assets/images/steps-positive-8-3-rd.svg",
      },
      {
        title: "Payments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/images/steps-positive-8-4-th.svg",
      },
      {
        title: "Description & Attachments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/images/steps-positive-8-5-th.svg",
      },
      {
        title: "Authorized Representative",
        subtitle: "Complete this part only of you appoint a representative.",
        step: "assets/images/steps-positive-8-6-th.svg",
      },
      {
        title: "Declaration",
        subtitle:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        step: "assets/images/steps-positive-8-7-th.svg",
      },
      {
        title: "Summary",
        subtitle: "Review the below information",
        step: "assets/images/steps-positive-8-8-th.svg",
      },
    ],
    taxPayerForm: {
      details: "Taxpayer Details",
      tin: "TIN",
      name: "Taxpayer Name",
      license: "CR / License",
      outlet: "Main Outlet",
      address: "Address",
    },
    returns: {
      zakat: "Zakat & CIT",
      amended: "Ammended by GAZT",
      year: "Assessment Year",
      assessmentAmount: "GAZT Assessment Amount",
    },
    payment: {
      paymentAmount: "Payment Amount",
      selectMethod: "Please select the payment method you would like to use",
      sadadPayment: "SADAD Payment",
      bankGuarantee: "Bank Guarantee",
      sadadInvoice: "SADAD Invoice",
      zakatInvoiceNumber: "Zakat SADAD Invoice Number",
      zakatPayableAmount: "Zakat Payable Amount",
      citInvoiceNumber: "CIT SADAD Invoice Number",
      citPayableAmount: "CIT Payable Amount",
      infoTitle: "Title",
      infoBody:
        "Please note that once you press this button, the amount and the related SADAD bill cannot be revised. Please ensure you pay any outstanding dues on the original re-assessment bill that were not paid submitted as payment.",
      acknowledgement:
        "I acknowledge that my application will not process until my payment is paid in full within 20 days",
      bankGuaranteeCheckbox1:
        "I acknowledge that I will submit the original bank guarantee in person to the General Authority of Zakat and Tax within 20 days from the date of submitting this application or the request will be automatically canelled.",
      bankGuaranteeCheckbox2:
        "I acknowledge that the bank guarantee submitted to the General Authority of Zakat and Tax must be valid and effective for at least one year and can be extended",
      bankGuaranteeCheckbox3:
        "I acknowledge that the Taz Identification Number (TIN) and the period under objection must be mentioned in the bank guarantee.",
    },
    objectionDetails: {
      zakat: "Zakat & CIT Return",
      referenceNumber: "Reference Number",
      assessmentYear: "Assessment Year",
      period: "Period",
      currency: "Currency",
      assessmentAmount: "GAZT Assessment Amount",
      returnDetails: "Return Details",
      viewReturn: "View Return",
      disputeText:
        "The following data has been changed by GAZT. Please edit the data you want to dispute.",
      currentAssets: "Current Assets",
      beginingBalance: "Begining Balance (SAR)",
      endingBalance: "Ending Balance (SAR)",
      cashInHand: "Cash in hand & at bank",
      shortTermInvestment: "Short Term Investment",
      accountReceivables: "Accounts Receivables & Debit Balances",
      merchandiseInventory: "Merchandise Inventory",
      accuredRevenues: "Accured Revenues",
      prepaidExpenses: "Prepaid Expenses",
      dueFromRelatedParties: "Due from Related Parties",
      otherAssets: "Other Current Assets",
      totalRevisedAmount: "Total Revisted Amount",
      disputedAmount: "Disputed Amount",
    },
    authorizedRepresentative: {
      title: "Authorized Representative",
      fullName: "Full Name",
      designation: "Designation",
      phoneNumber: "Phone Number",
      buildingName: "Building Name",
      fax: "Fax Number",
      levelAndStreetNumber: "Level & Street Number",
      email: "Email",
      city: "City",
    },
    declarationModule: {
      title: "Declaration",
      name: "Name of Applicant",
      position: "Position / Capacity",
      declaration:
        "I hereby declare that the above mentioned information is true and correct to the best of my knowledge and belief.",
    },
    successScreen: {
      objectionRequest: "Zakat Objection Request",
      successMessage:
        "We hace received your Objection Application. Please retain this number for future reference and communication. GAZT will assess your Objection Application and in case of any missing information will revert back to you.",
      referenceNumber: "Reference Number",
      confirmation: "Download Confirmation",
      form: "Download Form",
    },
  },
  ar: {
    dir: "rtl",
    bctitle1: "Objections & Reviews",
    bctitle2: "New Objection or Review",
    bctitle3: "New Zakat Objection",
    back: "رجوع",
    continue: "متابعة",
    confirm: "Confirm",
    objection: "Objection Details",
    dragAndDrop: "Drag and drop file to upload documentation",
    revisedAmount: "المبلغ الغير معترض عليه من المكلف",
    descriptionAndAttachment: "Description & Attachments",
    attachment: "المرفقات",
    edit: "Edit",
    objectionAndWithdrawl: "Objection Withdrawal",
    escalationToAppealComitee: "Escalation to Appeal Comitee",
    zakatObjectionDetails: "Zakat Objection Details",
    zakatObjection: "Zakat Objection",
    approved: "Approved",
    sar: "ريال سعودي",
    addForm: "Add Form",
    max: "Max",

    filesizeMessage: "يجب أن يكون حجم الملف أقل من 10 ميجا بايت.",
    zeroFilesizeMessage: "تعذر تحميل المرفقات",
    invalidFormat: "الرجاء استخدام صيغ الملفات المسموح بها فقط",
    fileAlreayExists: "يوجد ملف بنفس الاسم مرفق مسبقا",
    maxNoOfFiles: "لا يمكن تحميل أكثر من 10 مرفقات",
    process: [
      {
        title: "Taxpayer details",
        subtitle: "Complete below Details",
        step: "assets/images/steps-positive-8-1-st.svg",
      },
      {
        title: "تفاصيل الاعتراض",
        subtitle: "Complete below details",
        step: "assets/images/steps-positive-8-3-rd.svg",
      },
      {
        title: "Payments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/images/steps-positive-8-4-th.svg",
      },
      {
        title: "Description & Attachments",
        subtitle:
          "Please write reason for Objection and attach supporting documentation",
        step: "assets/images/steps-positive-8-5-th.svg",
      },
      {
        title: "الممثل الشرعي",
        subtitle: "Complete this part only of you appoint a representative.",
        step: "assets/images/steps-positive-8-6-th.svg",
      },
      {
        title: "Declaration",
        subtitle:
          "I hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct",
        step: "assets/images/steps-positive-8-7-th.svg",
      },
      {
        title: "Summary",
        subtitle: "Review the below information",
        step: "assets/images/steps-positive-8-8-th.svg",
      },
    ],
    taxPayerForm: {
      details: "Taxpayer Details",
      tin: "TIN",
      name: "Taxpayer Name",
      license: "CR / License",
      outlet: "Main Outlet",
      address: "Address",
    },
    returns: {
      zakat: "Zakat & CIT",
      amended: "Ammended by GAZT",
      year: "سنة الربط",
      assessmentAmount: "GAZT Assessment Amount",
    },
    payment: {
      paymentAmount: "Payment Amount",
      selectMethod: "Please select the payment method you would like to use",
      sadadPayment: "SADAD Payment",
      bankGuarantee: "Bank Guarantee",
      sadadInvoice: "SADAD Invoice",
      zakatInvoiceNumber: "Zakat SADAD Invoice Number",
      zakatPayableAmount: "Zakat Payable Amount",
      citInvoiceNumber: "CIT SADAD Invoice Number",
      citPayableAmount: "CIT Payable Amount",
      infoTitle: "Title",
      infoBody:
        "Please note that once you press this button, the amount and the related SADAD bill cannot be revised. Please ensure you pay any outstanding dues on the original re-assessment bill that were not paid submitted as payment.",
      acknowledgement:
        "I acknowledge that my application will not process until my payment is paid in full within 20 days",
      bankGuaranteeCheckbox1:
        "I acknowledge that I will submit the original bank guarantee in person to the General Authority of Zakat and Tax within 20 days from the date of submitting this application or the request will be automatically canelled.",
      bankGuaranteeCheckbox2:
        "I acknowledge that the bank guarantee submitted to the General Authority of Zakat and Tax must be valid and effective for at least one year and can be extended",
      bankGuaranteeCheckbox3:
        "I acknowledge that the Taz Identification Number (TIN) and the period under objection must be mentioned in the bank guarantee.",
    },
    objectionDetails: {
      zakat: "Zakat & CIT Return",
      referenceNumber: "الرقم المرجعي",
      assessmentYear: "سنة الربط",
      period: "الفترة",
      currency: "العملة",
      assessmentAmount: "GAZT Assessment Amount",
      returnDetails: "تفاصيل الإقرار",
      viewReturn: "View Return",
      disputeText:
        "The following data has been changed by GAZT. Please edit the data you want to dispute.",
      currentAssets: "Current Assets",
      beginingBalance: "Begining Balance (SAR)",
      endingBalance: "Ending Balance (SAR)",
      cashInHand: "Cash in hand & at bank",
      shortTermInvestment: "Short Term Investment",
      accountReceivables: "Accounts Receivables & Debit Balances",
      merchandiseInventory: "Merchandise Inventory",
      accuredRevenues: "Accured Revenues",
      prepaidExpenses: "Prepaid Expenses",
      dueFromRelatedParties: "Due from Related Parties",
      otherAssets: "Other Current Assets",
      totalRevisedAmount: "Total Revisted Amount",
      disputedAmount: "المبلغ المعترض عليه",
    },
    authorizedRepresentative: {
      title: "الممثل الشرعي",
      fullName: "الاسم الكامل",
      designation: "الصفة",
      phoneNumber: "Phone Number",
      buildingName: "اسم البناية",
      fax: "رقم الفاكس",
      levelAndStreetNumber: "الاقامة و اسم الشارع",
      email: "Email",
      city: "City",
    },
    declarationModule: {
      title: "Declaration",
      name: "Name of Applicant",
      position: "Position / Capacity",
      declaration:
        "I hereby declare that the above mentioned information is true and correct to the best of my knowledge and belief.",
    },
    successScreen: {
      objectionRequest: "Zakat Objection Request",
      successMessage:
        "We hace received your Objection Application. Please retain this number for future reference and communication. GAZT will assess your Objection Application and in case of any missing information will revert back to you.",
      referenceNumber: "Reference Number",
      confirmation: "Download Confirmation",
      form: " تحميل النموذج",
    },
  },
};

export const ApiConstants = {
  getObjectionData: "sap/opu/odata/SAP/Z_OBJ_ZNOB_SRV/ZNOB_HeaderSet",
  getReferenceNumberDetails: "sap/opu/odata/SAP/Z_OBJ_ZNOB_AMT_SRV/ZNOB_AmtSet",
  saveObjection: "sap/opu/odata/SAP/Z_OBJ_ZNOB_SRV/ZNOB_HeaderSet",
  fetchPaymentDetails: "sap/opu/odata/SAP/Z_OBJ_ZNOB_REV_AMT_SRV/secamtSet",
  attachment: "sap/opu/odata/SAP/ZDP_INDTAX_ATT_SRV",
};
