export const permitDeregLabels = {
    langz: {
        eng: {
            dir: "ltr",
            menuEng: [
                {
                  t1: "License De-registration",
                  t2: "Select one of the following Outlets",
                  t3: "assets/image/components-steps-positive-5-1-st.svg",
                },
                {
                  t1: "De-registration Details",
                  t2: "Complete following Details",
                  t3: "assets/image/components-steps-positive-5-2-nd.svg",
                },
                {
                  t1: "Attachments",
                  t2: "Please provide a copy of following documents",
                  t3: "assets/image/components-steps-positive-5-3-rd.svg",
                },
                {
                  t1: "Declaration",
                  t2: "Complete below Details",
                  t3: "assets/image/components-steps-positive-5-4-th.svg",
                },
                {
                  t1: "Summary",
                  t2: "Review the below information",
                  t3: "assets/image/components-steps-positive-5-5-th.svg",
                },
              ],
            attachTypes: [
              "Copy of License after closing / Update",
              "Ownership Selling / Transfer Agreement",
              "Copy of CR after closing / Update",
              "Copy of Contract closing / Update"
            ],
            idTypes: [
              { name: "Company ID", value: "ZS0005" },
              {
                name: "National ID",
                value: "ZS0001",
              },
              { name: "Iqama ID", value: "ZS0002" },
              { name: "GCC ID", value: "ZS0003" },
            ],
            title1: "Profile >",
            title2: "Tax De-registration >",
            title3: "Zakat & CIT De-registration >",
            title4: "License De-registration",
            subtitle1: "Select one of the following Outlets",
            licenseDeReg: "License De-registration",
            back: "Back",
            continue: "Continue",
            addr: "Address",
            outNm: "Outlet Number",
            outlt: "Outlet",
            slctprmt: "Select Permit for Main Activity",
            slctMnActvty: "Select Main Activity",
            slctPrmts: "Select Permits to deregister",
            prmtNo: "Permit Number",
            vldFrm: "Valid From",
            dregDt: "De-registration Date",
            dregReason: "De-registration Reason",
            closed: "Closed",
            trnsfr: "Transfer",
            tin: "TIN",
            idTyp: "ID Type",
            idNum: "ID Number",
            name: "Name",
            decName: "Name",
            fatherName: "Father’s Name",
            gfName: "Grand Father's Name",
            familyName: "Surname",
            dtofBrth: "Date of Birth",
            attchTxt1: "Drag and drop file to upload documentation",
            attchTxt2: "File size should be less than 1 MB.",
            cntctNo: "Contact Number",
            desig: "Designation",
            Date: "Date",
            dclrMsg: "I delcare that all entered data are valid",
            outltTyp: "Outlet Type",
            prmtTyp: "Permit Type",
            declrtn: "Declaration",
            cnfrm: "Confirm",
            lsDereg: "License De-registration",
            ackTxt1: "The License De-registration request has been sent to GAZT.",
            ackTxt2: "The request will be reviewed by GAZT, if the request is rejected due to missing data GAZT",
            ackTxt3: "will notify you via SMS and email.",
            cmmrclName: "Commercial Name",
            refNo: "Reference Number",
            subDt: "Submission Date",
            dwnldCnfrm: "Download Confirmation",
            ZakatNCIT: "Zakat & CIT De-registration",
            goto: "Go to Dashboard",
            valdateID: "Validate ID",
            ok: "OK",
            cancel: "Cancel",
            close: "Close",
            crNum: "C/R Number",
            licensNum: "License Number",
            contractNum: "Contract Number",
            txt1: "1. The Maximum number of attachments that can be uploaded is 5",
            txt2: "2. Alert, you must adjust the settings of the scanner so that the zip file size is less than 1 MB",
            txt3: "3. The recommended settings for your scanner is : 1024 * 745",
            txt4: "4. Choose only file with extension DOC, DOCX, XLS, XLSX, PDF, JPG",
            txt5: "5. Please make sure that the attached file is free of any viruses or hacking programs as any file containing this type of file will be rejected automatically.",
            mandatory: "Mandatory",
            mainOutlt: "Main-outlet",
            subOutlt: "Sub-outlet",
            errs: {
              e3: "Invalid Date of Birth",
              e4: "Invalid entry",
              slct1outlt: "Select Atleast one Outlet for Which Permit to be Deregistered.",
              slctprmterr: "Please Select Permit for Main Activity",
              slctMnActvty: "Please Select Main Activity",
              slct1: "select any one",
              dregDtErr: "Please provide Deregistration date",
              dregReasonErr: "Please select reason for deregistration",
              slctIDTypErr: "Please select ID Type",
              entrIDNumErr: "Please enter ID Number",
              entrNameErr: " Please enter Name",
              entrFatherNameErr: "Please enter Father's Name",
              entrGFName: "Please enter Grand Father's Name",
              entrFmlyName: "Please enter Family Name",
              entrDtofBrth: "Please enter Date of Birth",
              provdName: "Please provide name", 
              cntctErr1: "Please provide Contact Number",
              cntctErr2: "Number should be start with 009665",
              cntctErr3: "Number should be of 14 digits",
              provdDesg: "Please Provide designation",
              allPrmtsErr: "All Permit are getting deregistered so please select Outlet deregistration",
              err206: "Dear Taxpayer, you have a Registration Change Application saved in draft mode, do you want to discard it and proceed for Deregistration Application?",
              err112: "Dear Taxpayer, you already have an application saved in draft mode for Permit/Outlet/TIN deregistration, do you want to discard it and proceed for new application?",
              fileError: "File size should be less than 1 MB",
              fileType: "Choose only file with extension DOC, DOCX, XLS, XLSX, PDF, JPG",
              tinReq: "Please provide the TIN",
              attchReq: "Please upload a file for relevant attachment",
              provdDec: "Please select declaration checkbox",
              drgDtVldtn: "Deregistration date cannot be before Valid from date",
              drgDtVldtn1: "Deregistration date cannot be in future",
              dobVldtn: "Please Select Date of Birth less than Deregistration Date ",
              dobVldtn1: "Date of Birth Cannot be in Future",
              sameTinErr: "Cannot be transfered to same TIN",
              fileError1: "File Name,Doc Type,Ret.Guid and File Content can not be blank in action N"
            }
        },
        arb: {
            dir: "rtl",
            menuArb: [
              {
                t1: "إلغاء تسجيل الرخصة",
                t2: "الرجاء اختيار احد الفروع التالية",
                t3: "assets/image/components-steps-positive-5-1-st.svg",
              },
              {
                t1: "تفاصيل الغاء التسجيل ",
                t2: "الرجاء إكمال البيانات التالية",
                t3: "assets/image/components-steps-positive-5-2-nd.svg",
              },
              {
                t1: "المرفقات",
                t2: " يرجى تقديم نسخة من الوثائق التالية",
                t3: "assets/image/components-steps-positive-5-3-rd.svg",
              },
              {
                t1: "التعهد",
                t2: "أكمل التفاصيل أدناه",
                t3: "assets/image/components-steps-positive-5-4-th.svg",
              },
              {
                t1: "ملخص",
                t2: "الرجاء مراجعة المعلومات التالية",
                t3: "assets/image/components-steps-positive-5-5-th.svg",
              },
            ],
          attachTypes: [
            " نسخة من الترخيص بعد إغلاق / تحديث",
            " عقد مبايعة نقل الملكية",
            " نسخة من السجل التجاري بعد إغلاق / تحديث",
            " نسخة من العقد بعد إغلاق / تحديث"
          ],
          idTypes: [
            { name: "رقم الشركة", value: "ZS0005" },
              {
                name: "رقم الهوية الوطنية",
                value: "ZS0001",
              },
              { name: "رقم الإقامة", value: "ZS0002" },
              { name: "رقم هوية المواطن الخليجي", value: "ZS0003" },
          ],
          title1: "الملف الشخصي >",
          title2: "إلغاء التسجيل في الضريبة >", 
          title3: "إلغاء التسجيل في الزكاة و ضريبة الدخل >",
            title4: "إلغاء تسجيل الرخصة",
            subtitle1: "الرجاء اختيار احد الفروع التالية",
            licenseDeReg: "إلغاء تسجيل الرخصة",
            back: "رجوع",
            continue: "التالي",
            addr: "العنوان",
            outNm: " رقم الفرع",
            outlt: "فرع",
            slctprmt: "  اختر ترخيص للنشاط الرئيسي",
            slctMnActvty: " اختر النشاط الرئيسي",
            slctPrmts: " الرجاء اختيار الترخيص لأيقافة",
            prmtNo: " رقم الترخيص",
            vldFrm: " صالحة من",
            dregDt: " تاريخ الايقاف/الشطب  ",
            dregReason: " سبب الايقاف ",
            closed: "اغلاق",
            trnsfr: "نقل",
            tin: " الرقم المميز",
            idTyp: " نوع الهوية",
            idNum: " رقم الهوية",
            name: " الاسم الأول",
            fatherName: " اسم الاب",
            gfName: " اسم الجد",
            familyName: " الكنية",
            dtofBrth: " تاريخ الميلاد",
            attchTxt1: "اسحب و أسقط ملف لتحميل الوثائق",
            attchTxt2: "بأقصى حجم 1 ميجا بايت",
            decName: "الاسم",
            cntctNo: " رقم الاتصال (009665)",
            desig: "الصفة",
            Date: "تاريخ",
            dclrMsg: " أتعهد بأن جميع البيانات المدخلة صحيحة",
            outltTyp: "نوع الفرع",
            prmtTyp: " نوع الترخيص ",
            declrtn: "التعهد",
            cnfrm: "تأكيد",
            lsDereg: "إلغاء تسجيل الرخصة",
            ackTxt1: "تم استلام طلب إلغاء تسجيل الرخصة بنجاح",
            ackTxt2: "سيتم مراجعة الطلب من قبل الهيئة العامة للزكاة والدخل, في حال رفض الطلب لوجود معلومات ناقصة",
            ackTxt3: "سوف يصلك رسالة نصية على الهاتف والبريد الالكتروني",
            cmmrclName: "الاسم التجاري",
            refNo: "الرقم المرجعي",
            subDt: "تاريخ التسليم",
            dwnldCnfrm: "تحميل تأكيد الاستلام",
            ZakatNCIT: "إلغاء التسجيل في الزكاة او ضريبة الدخل",
            goto: "الذهاب إلى لوحة التحكم",
            valdateID: "التحقق من الهوية",
            ok: "موافق",
            cancel: "إلغاء",
            close: "إغلاق",
            crNum: "رقم السجل التجاري",
            licensNum: "رقم الرخصة",
            contractNum: "رقم العقد",
            txt1: "1.يجب ان لايتعدى عدد المرفقات لعملية تقديم الإقرار / او التعديل على الإقرار عن 5 مرفقات",
            txt2: "2.تنبيه, يجب ضبط اعدادات الماسح الضوئي بحيث يكون حجم الملف المضغوط أقل من. 1MB",
            txt3: "3.الاعدادات الموصى بها للماسح الضوئي هي: 1024 * 745",
            txt4: "4.الرجاء إرفاق ملف من الامتدادت التالية فقط DOC, DOCX, XLS, XLSX, PDF, JPG",
            txt5: "5.يرجى التأكد من خلو الملف المرفق من أي فيروسات أو برامج قرصنة حيث سيتم رفض أي ملف يحتوي على هذا النوع من الملفات تلقائيًا.",
            mandatory: "إجباري",
            mainOutlt: "Main-outlet",
            subOutlt: "Sub-outlet",
            errs: {
              e3: "تاريخ الميلاد المدخل غير صحيح ",
              e4: "يجب تحديد التاريخ",
              slct1outlt: "اختر على الاقل فرع واحد للترخيص المراد إيقافه",
              slctprmterr: "الرجاء اختيار ترخيص للنشاط الرئيسي",
              slctMnActvty: "الرجاء اختيار نشاط رئيسي",
              slct1: "الرجاء تحديد خيار واحد فقط",
              dregDtErr: "الرجاء إدخال تاريخ الايقاف / الشطب",
              dregReasonErr: "من فضلك اختر سبب للإيقاف",
              slctIDTypErr: "الرجاء اختيار نوع الهوية",
              entrIDNumErr: "الرجاء ادخال رقم الهوية",
              entrNameErr: " الرجاء قم بتزويد الاسم",
              entrFatherNameErr: "الرجاء إدخال اسم الأب",
              entrGFName: "الرجاء إدخال اسم الجد",
              entrFmlyName: "الرجاء إدخال اسم العائلة",
              entrDtofBrth: " الرجاء ادخال تاريخ الميلاد",
              provdName: "الرجاء قم بتزويد الاسم", 
              cntctErr1: " الرجاء قم بتزويد رقم الاتصال",
              cntctErr2: "رقم الهاتف يجب أن يبدأ بـ 00966",
              cntctErr3: "رقم الهاتف يجب ان يتكون من 14 رق",
              provdDesg: "الرجاء قم بتزويد المنصب",
              allPrmtsErr: "جميع التراخيص سوف يتم ايقافها / اغلاقها, الرجاء اختيار الفرع لإيقافه / اغلاقه بما في ذلك التراخيص التابعه له",
              err206: "عزيزي المكلف, يوجد لديك طلب تغيير تسجيل محفوظ كمسودة, هل تريد حذفه وإكمال طلب ايقاف التسجيل؟",
              err112: "عزيزي المكلف ، لديك بالفعل طلب تم حفظه في وضع المسودة لإلغاء تسجيل التصريح / منفذ البيع / رقم المكلف ، هل تريد تجاهله والمضي قدمًا في طلب جديد؟",
              fileError: "يجب ان يكون حجم الملف المرفق اقل من 1 ميجا",              
              fileType: "الرجاء إختيار ملف من الإمتدادات التالية فقط DOC, DOCX, XLS, XLSX, PDF, JPG",
              tinReq:  "الرجاء قم بتزويد الرقم المميز",
              attchReq: "ارفاق الملف الزامي, الرجاء ارفق الملف",
              provdDec: "الرجاء تحديد خانة التعهد",
              drgDtVldtn: "تاريخ التفعيل يجب ان لا يكون قبل تاريخ بدء الصلاحية",
              drgDtVldtn1: "تاريخ التفعيل يجب ان لا يكون تاريخ مستقبلي",
              dobVldtn: "الرجاء اختيار تاريخ ميلاد يكون قبل تاريخ الايقاف",
              dobVldtn1: "تاريخ الميلاد يجب ان لا يكون تاريخ مستقبلي",
              sameTinErr: "لا يمكن التحويل إلى نفس الرقم المميز",
              fileError1: "عذراً، لا يمكن أن يكون اسم الملف، نوع الملف، ومحتوى الملف فارغاً للنشر"
            }
        }
    },
};