export const renewalwarehouseconstants = {
    langz: {
      eng: {
        dir: "ltr",
        renewalwarehouse:
        {
          nav:{
            t1:"Tax Management > Excise Services > Warehouse >",
            t2:"Warehouse License Renewal",
            t3:"Back", 
            edit:"Edit",           
            continue:"Continue" ,
            confirm:"Confirm" ,
            save:"Save",
            yes:"Yes",
            no:"No",      
            close: "Close",   
            saveasdraft:"Save As Draft"   ,
            btn1:"Ok",
          },
          
          step1:{
            t1:"Confirmation",
            t2:"Do You Want Submit New Application",
            t3:"Select the Application Number you want to Proceed",
            t4:"Select",
            t5:"Application Number",
            t6:"Warehouse License Number",
          },
          step2:{
            t1:"Warehouse Information",
            t2:"Please provide the information about the type of warehouse and relevant excise goods",
            t3:"Warehouse",
            t4:"FIN",
            t5:"Business Name",
            t6:"Choose the Warehouse license to be renewed",
            t7:"Select Warehouse No ",
            t8:"Expiry Date ",
            t9:"Do you want to extend the validity for Renewal Period beyond 1 year?",
            t10:"Select the period for which you want to increase validity",
            t11:"What do you want to change?",
            t12:"Type & Products for Warehouse",
            t13:"Warehouse Dimensions",
            t14:"Warehouse Identification",
            t15:"Warehouse Manager Information",
            t16:"Warehouse Ownership",
            t17:"Bank Guarantee Information",
            yes:"Yes",
            no:"No",
            years:"Years",
            popup:{
                h1:"Warehouse License ",
                t1:"In order to apply for the renew in a license for the tax warehouse, the taxpayer must:",
                t2:"Have a valid warehouse license",
                t3:"Comply with all regulations and general guidelines laid down by the GAZT",
                t4:"I declare that I meet the above requirements",
                renewbtn:"Renew Warehouse ",
            }
          },
          step3:{
            t1:"Warehouse Information",
            t2:"Please provide the information about the type of warehouse and relevant excise goods",
            t3:"Do You want to change some information in the license as a part of the renewal?",
            t4:"Type & Product",
            t5:"Please provide the information about the type of warehouse and relevant excise goods",
            t6:"For what purpose warehouse will be used?",
            t7:"Valid From",
            t8:"Type of excise goods that will be manufactured or stored",
            t9:"Warehouse Identification & Address",
            t10:"Please enter wasel address for the warehouse",
            t11:"Valid From",
            t12:"Latitude",
            t13:"Longitude",
            t14:"Warehouse Ownership",
            t15:"Have you leased the warehouse?",
            t16:"ID type",
            t17:"ID Number",
            t18:"Nationality of the Owner",
            t19:"Name of the Owner",
            t20:"CR. No",
            t21:"TIN",
            t22:"Company Name",
            t23:"Address",
            t24:"Scanned copy of the agreement for Lease",
            t25:"Warehouse Dimensions",
            t26:"Size (Meters)",
            t27:"Length",
            t28:"Width",
            t29:"Storage Capacity",
            t30:"Square Meters",
            t31:"Height",
            t32:"Scanned copy of the agreement for Lease",
            // t33:"",
            t34:"Warehouse Manager Information",
            t35:"ID Type",
            t36:"ID Number",
            t37:"Date of Hiring",
            t38:"First Name",
            t39:"Surname",
            t40:"Middle Name",
            t41:"Father’s Name",
            t42:"Grandfather’s Name",
            t43:"Phone Number",
            t44:"Email",
            t45:"Bank Guarantee Information",
            t46:"Bank Guarantee Information",
            t47:"Additional Information",
            t48:"Are you in a financially sound position?",
            t49:"Declaration",
            t50:"Name",
            t51:"Designation",
            t52:"ID type",
            t53:"ID Number",
            t54:"I agree with",
            t55:"Terms and Conditions.",
            explain:"Explain the answer",
            file:"File Attachment",
            b1:"Bank Guarantee",
            b2:"Please review Bank Guarantee Information to proceed",
            b3:"Cancel",
            b4:"Bank Guarantee Info",
            
          },
          step4:{
            t1:"Type & Product ",
            t2:"Please provide the information about the type of warehouse and relevant excise goods",
            t3:"For what purpose warehouse will be used?",
            t4:"Valid From",
            t5:"To obtain a warehouse license for a storage warehouse you should meet all the below conditions:",
            t6:"1.The quality of excise goods being held as an average over the course of 12 calendar months is more than one of the following:",
            t7:"a.10,000,000 Liars of Soft Drink, Energy Drink or Sweetened Beverages",
            t8:"b.1,000,000,000 cigarettes or other individual units of tobacco products.",
            t9:"c.500,000 kilograms of other tobacco products",
            t10:"2.At least 70% of the Excise goods held at the location shall be removed from the Kingdom  under suggestion of Tax",
            t11:"3.The permission is granted for the usage of the location as a Tax Warehouse by the Board of Directors.",
            t12:"If any of the above are met , GAZT will not issue the warehouse license",
            t13:"What types of excise goods will be manufactured or stored in the warehouse?",
            t14:"I declare that i meet the above requirements.",
          },
          step5:{
            t1:"Warehouse Identification & Address",
            t2:"Please enter wasel address for the warehouse",
            t3:"Warehouse Name",
            t4:"Only alphabets allowed",
            t5:"Building Number",
            t6:"Only Digits allowed",
            t7:"Maximum 15 Digits",
            t8:"Street Name",
            t9:"Maximum 40 Characters allowed",
            t10:"Region / District",
            t11:"City",
            t12:"Postal Code",
            t13:"Only Digits allowed",
            t14:"Maximum 5 Digits",
            t15:"Add. No",
            t16:"Maximum 10 Digits",
            t17:"Only Digits allowed",
            t18:"Quarter",
            t19:"Maximum 40 Characters allowed",
            t20:"Only Digits allowed",
            t21:"Lattitude ",
            t22:"Only Digits allowed",
            t23:"Maximum 15 Digits",
            t24:"Maximum 90 allowed",
            t25:"Longitude",
            t26:"Only Digits allowed",
            t27:"Maximum 15 Digits",
            t28:"Maximum 180 allowed",
            t29:"Maximum 40 Characters allowed",
            
          },
          step6:{
            t1:"Warehouse Ownership ",
            t2:"Complete below details",
            t3:"Have you leased the warehouse?",
            t4:"Owner Type",
            t5:"ID type",
            t6:"ID Number",
            t7:"Only Digits allowed",
            t8:"Minimum 8 Digits allowed",
            t9:"Maximum 16 Digits allowed",
            t10:"Nationality of the Owner",
            t11:"Name of the Owner",
            t12:"Phone Number",
            t13:"Only Numbers allowed",
            t14:"Minimum 9 Digits",
            t15:"Maximum 14 Digits",
            t16:"Email",
            t17:"Please Enter Valid Email Address",
            t18:"Please upload the scanned copy of the agreement for lease",
            t19:"CR. No",
            t20:"Only 10 Numbers Allowed",
            t21:"Minimum 9 Digits",
            t22:"Maximum 14 Digits",
            t23:"TIN",
            t24:"Only Numbers Allowed",
            t25:"Minimum 8 Digits",
            t26:"Maximum 16 Digits",
            t27:"Company Name",
            t28:"Only 40 characters allowed",
            t29:"Address",
            t30:"Phone Number",
            t31:"Only Numbers allowed",
            t32:"Minimum 10 Digits",
            t33:"Maximum 14 Digits",
            t34:"Please upload the scanned copy of the agreement for lease",
            t35:"When did you Lease / Rent the warehouse?",
            t36:"What is the Expiry Date of the Lease / Rent Agreement?",
            t37:"Please Select Owner Type",
            t38:"Please Select Id Type",
            t39:"Only 40 characters allowed"
            // t37:"",
          },
          step7:{
            t1:"Warehouse Dimensions",
            t2:"Please provide the dimensions of the warehouse ",
            t3:"Size (Meters)",
            t4:"Length",
            t5:"Only 5 Numeric and 2 decimals Allowed",
            t6:"Minimum 0.5",
            t7:"Maximum 1000",
            t8:"Width",
            t9:"Only 5 Numeric and 2 decimals Allowed",
            t10:"Minimum 0.5",
            t11:"Maximum 1000",
            t12:"Height",
            t13:"Only 5 Numeric and 2 decimals Allowed",
            t14:"Minimum 0.5",
            t15:"Maximum 1000",
            t16:"Storage Capacity",
            t17:"Cubic Meters",
            t18:"Only 5 Numeric and 2 decimals Allowed",
            t19:"Minimum 0.5",
            t20:"Maximum 1000",
            t21:"Square Meters",
            t22:"Only 5 Numeric and 2 decimals Allowed",
            t23:"Minimum 0.5",
            t24:"Maximum 1000",
            t25:"The above information should be in line with dimensions document obtained from Municipality or  Civil Affairs", 
            t26:"Please update a copy of the Municipal License",
          },
          step8:{
            t1:"Warehouse Manager Information",
            t2:"Complete below details",
            t3:"ID Type",
            t4:"ID Number",
            t5:"Only Digits allowed",
            t6:"Minimum 8 Digits allowed",
            t7:"Maximum 16 Digits allowed",
            t8:"Nationality of the Owner",
            t9:"Date of Hiring",
            t10:"Title",
            t11:"First Name",
            t12:"Surname",
            t13:"Middle Name",
            t14:"Father’s Name",
            t15:"Grandfather’s Name",
            t16:"Phone Number",
            t17:"Only Numbers allowed",
            t18:"Minimum 10 Digits",
            t19:"Maximum 14 Digits",
            t20:"Email",
            t21:"Please Select Id Type",
            t22: {
              t1: "ID Number",
              t2: "DOB",
              btn1: "Validate ID",
            },
            t23: "Date of Birth is Required.",
          },
          step9:{
            t1:"Bank Guarantee Information",
            t2:"Provide the ‘total value of the retail selling price’ for different categories. System will automatically calculate the ‘Initial Bank Guarantee Value’. Total Value for Retail Selling Price* (RSP) includes the Excise Tax Amount.",
            t3:"Please provide the monthly average of projected amount for last one year for the warehouse.",
            t4:"Tobacco products must have separate Warehouse (Tobacco cannot be manufactured or stored with Soft Drinks,Energy Drinks & Sweetened Beverages).",
            t5:"Please provide the actual bank guarantee letter to GAZT once your application is accepted.",
            t6:"Total Value for Retail Selling Price* (RSP) including Excise Tax is the summation of the RSP Values of Moved, Stored and Released Goods",
            t7:"Retail Selling Price",
            t8:"Product Type",
            t9:"Good Types",
            t10:"Quantity",
            t11:"Unit of Measure",
            t12:"Total RSP Value",
            t13:"Initial Bank Guarantee Value",
            t14:"Please provide the bank guarantee letter from your bank which should be redeemable if presented to the bank",
            t15:"Range of value allowed is 0 to 999,999,999,999.99",
            t16:"Only 25 Numbers allowed"
          },
          step10:{
            t1:"Additional Information",
            t2:"Please provide the following additional information",
            t3:"Are you in a financially sound position?",
            t4:"Explain the answer",
            t5:"Have you or your legal representative in the management of the establishment through which you carry your activities,been previously convicted of financial crimes without being subsequently restored to good standing?",
            t6:"Explain the answer",
            t7:"Do you have an administrative system to help administer a Tax Warehouse, which is compliant with the provisions of the Law and these Regulations?",
            t8:"Explain the answer",
            t9:"Do you have safety and security measures in place limiting accidents as determined by concerned authorities?",
            t10:"Explain the answer",
          },
          step11:{
            t1:"Declaration",
            t11:"Complete below details",
            t2:"Name",
            t3:"Designation",
            t4:"ID Type",
            t5:"ID Number",
            t6:"Only Digits allowed",
            t61:"Minimum 8 Digits allowed",
            t7:"Maximum 16 Digits allowed",
            t8:"Date",
            t9:"I undersigned that all information contained in this application is true and correct and that I am authorized by regulations to complete this request",
            t10:"Only 40 characters allowed",
            t12:"Only characters allowed",
          },
          step12:{
              t1:"Summary",
              t2:"Review the below information",
              s1:{
                t1:"Warehouse",
                t2:"FIN",
                t3:"Business Name",
                t4:"Warehouse usage purpose",
                t5:"Expiry Date",
                t6:"Extend the validity for Renewal Period beyond 1 year",
                t7:"Select the period for which you want to increase validity",
              },
              s2:{
                t1:"Type & Product",
                t2:"For what purpose warehouse will be used?",
                t3:"Type of excise goods that will be manufactured or stored",
              },
              s3:{
                t1:"Warehouse Identification & Address",
                t2:"Please enter wasel address for the warehouse",
                t3:"Building Name",
                t4:"Street Name",
                t5:"Region/District",
                t6:"City",
                t7:"Postal Code",
                t8:"Address Number",
                t9:"Quarter",
                t10:"Latitude",
                t11:"Longitude",
              },
              s4:{
                t1:"Warehouse Ownership",
                t2:"Have you leased the warehouse?",
                t3:"ID type",
                t4:"ID Number",
                t5:"Nationality of the Owner",
                t6:"Name of the Owner",
                t7:"Mobile",
                t8:"Email Id",
                t9:"CR. No",
                t10:"TIN",
                t11:"Company Name",
                t12:"Address",
                t13:"Mobile",
                t14:"Scanned copy of the agreement for Lease",
              },
              s5:{
                t1:"Warehouse Dimensions",
                t2:"Size (Meters)",
                t21:"Length",
                t3:"Width",
                t4:"Storage Capacity",
                t5:"Cubic Meters",
                t6:"Square Meters",
                t7:"Height",
                t8:"Scanned copy of the agreement for Lease", 
              },
              s6:{
                t1:"Warehouse Manager Information",
                t2:"ID Type",
                t3:"ID Number",
                t4:"Nationality of the Owner",
                t5:"Title",
                t6:"First Name",
                t7:"Surname",
                t8:"Middle Name",
                t9:"Father’s Name",
                t10:"Grandfather’s Name",
                t11:"Phone Number",
                t12:"Email",
                t13:"Date of Hiring"
              },
              s7:{
                t1:"Bank Guarantee Information",
                t2:"Bank Guarantee Information",
                t3:"SAR",
              },
              s8:{
                t1:"Additional Information",
                t2:"Are you in a financially sound position?",
                t3:"File Attachment",
                t4:"Explain the answer",
                t5:"Have you or your legal representative in the management of the establishment through  which you carry your activities,been previously convicted of financial crimes without being subsequently restored to good standing?",
                t6:"File Attachment",
                t7:"Explain the answer",
                t8:"Do you have an administrative system to help administer a Tax Warehouse, which is compliant with the provisions of the Law and these Regulations?",
                t9:"File Attachment",
                t10:"Explain the answer",
                t11:"Do you have safety and security measures in place limiting accidents as determined by concerned authorities?",
                t12:"File Attachment",
                t13:"Explain the answer",
              },
              s9:{
                t1:"Declaration",
                t2:"Name",
                t3:"Designation",
                t4:"ID type",
                t5:"ID Number",
                t6:"I agree with",
                t7:"Terms and Conditions.",
              }
          },
          step13:{
            t1:"Acknowledgement",
            t2:"GAZT acknowledges the receipt of your Renewal Warehouse License Registration ",
            t3:"Application Number",
            t4:"Date",
            t5:"Please retain this number for future reference and communication. GAZT will process your request and if needed will contact for any additional information. For further information please contact to help desk.",
            t6:"Download Acknowledgement",
            t7:"Download Form",
          },
          plcholders:{
            t1:"Zaed Warehouse",
            t2:"Olaya St",
            t3:"Postal Code",
            t4:"Add. No",
            t5:"Quarter",
            t6:"zaed@gmail.com",
            t7:"Id Number",
            t8:"Date of Hiring",
            t9:"Name Surname",
            t10:"Surname",
            t11:"Middle Name",
            t12:"Father Name",
            t13:"Grand Father Name",
            t14:"Email Id",
            dragdrop: "Drag and drop file to upload documentation",
            max:"2MB max",
            reason:"Reason"
          },
          termsConditions:{
            t1:"Terms and Conditions :",
            t2:"This form has to be completed by a legal representative of the entity, penalties set forth in GAZT regulation will be applied if the information provided in the form is incorrect without prejudice to the penalties set forth in other applicable regulations in the Kingdom.",
            t3:"The entity must be established as per the applicable regulations in the kingdom.",
            t4:"The entity has to maintain books and accounts regularly as per regulations in GAZT.",
            t5:"GAZT has the right to obtain and review the financial statements and accounting records of the entity.",
            t6:"GAZT has the right to obtain and review the financial statements and accounting records of the owner/s.",
            t7:"The prescribed fees must be paid as per GAZT regulations.",
            t8:"The entity must notify GAZT of any major changes related to the warehouse in accordance with terms and procedures set forth in GAZT regulations.",
            t9:"Entities established prior to the issuance of Excise Tax regulations are exempted from answering (9,10,12,13) in this form.",
            t10:"This license might be cancelled or suspended in accordance to the cases listed as per GAZT regulations.",
            dashboard:"GoTo Dashboard",
          }

          
        },       

      },

      arb: {
        dir: "rtl",
        renewalwarehouse:
        {
            nav:{
              t1:"إدارة الضريبة> خدمات انتقائية> مستودع>",
              t2:"طلب تجديد رخصة مستودع ضريبي",
              t3:"رجوع", 
              edit:"تعديل",           
              continue:"متابعه" ,
              confirm:"تأكيد" ,
              save:"حفظ",
              yes:"نعم",
              no:"لا",      
              close: "إغلاق",  
              saveasdraft:"حفظ كمسودة"  ,
              btn1:"موافق"
            },
            plcholders:{
              t1:"Zaed Warehouse",
              t2:"شارع العليا",
              t3:"الرمز البريدي",
              t4:"أضف الرقم",
              t5:"الربع",
              t6:"zaed@gmail.com",
              t7:"رقم الهوية",
              t8:"تاريخ التعيين",
              t9:"Name Surname",
              t10:"اللقب",
              t11:"الاسم الأوسط",
              t12:"اسم الأب",
              t13:"اسم الجد",
              t14:"البريد الالكتروني",
              dragdrop: "إسحب وأسقط ملف لتحميل الوثائق",
              max: "كحد أقصى 2 ميجا بايت",
              reason:"السبب"
             
            },
            step1:{
              t1:"تأكيد",
              t2:"هل تريد تقديم طلب جديد",
              t3:"اختر رقم الطلب المراد معالجته",
              t4:"اختيار",
              t5:"الرقم المرجعي",
              t6:"رقم رخصة المستودع",
            },
            step2:{
              t1:"معلومات المستودع",
              t2:"يرجى تقديم المعلومات حول نوع المستودع والسلع الانتقائية ذات الصلة",
              t3:"المستودع",
              t4:"الرقم الضريبي",
              t5:"اسم المنشأة",
              t6:"اختر رخصة المستودع الضريبي المراد تجديدها ",
              t7:"حدد رقم المستودع ",
              t8:"تاريخ الإنتهاء ",
              t9:"هل تريد تمديد صلاحية فترة التجديد لأكثر من سنة؟",
              t10:"حدد الفترة التي تريد زيادة الصلاحية؟",
              t11:"ما هي المعلومات المراد تعديلها؟",
              t12:"نوع النشاط والسلع",
              t13:"أبعاد ومساحة المستودع",
              t14:"تعريف المستودع",
              t15:"معلومات مدير المستودع",
              t16:"ملكية المستودع",
              t17:"معلومات الضمان البنكي",
              yes:"نعم",
              no:"لا",
              years:"السنوات",
              popup:{
                  h1:"رخصة مستودع ",
                  t1:"لكي تتمكن من طلب تجديد رخصة مستودع ضريبي، يجب على المكلف:",
                  t2:"أن يكون حاصلا على رخصة مستودع ضريبي سارية المفعول",
                  t3:"الامتثال لجميع اللوائح والتوجيهات العامة التي وضعتها الهيئة ",
                  t4:"أقر بأنني أفي بالمتطلبات المذكورة أعلاه",
                  renewbtn:"تجديد المستودع",
              }
            },
            step3:{
              t1:"معلومات المستودع",
              t2:"يرجى تقديم المعلومات حول نوع المستودع والسلع الانتقائية ذات الصلة",
              t3:"هل تريد تغيير بعض المعلومات في الرخصة كجزء من التجديد؟",
              t4:"النوع والمنتج",
              t5:"يرجى تقديم المعلومات حول نوع المستودع والسلع الانتقائية ذات الصلة",
              t6:"لأي غرض سيتم استخدام المستودع؟",
              t7:"صالح من",
              t8:"ما هو نوع السلع الإنتقائية التي سيتم انتاجها او تخزينها في المستودع؟",
              t9:"عنوان المستودع",
              t10:"الرجاء إدخال عنوان واصل للمستودع",
              t11:"صالح من",
              t12:"خط العرض",
              t13:"خط الطول",
              t14:"ملكية المستودع",
              t15:"هل انت مستأجر المستودع؟",
              t16:"نوع الهوية",
              t17:"رقم الهوية",
              t18:"جنسية المالك",
              t19:"اسم المالك",
              t20:"رقم السجل التجاري",
              t21:"الرقم المميز",
              t22:"اسم الشركة",
              t23:"العنوان",
              t24:"نسخة ممسوحة ضوئيًا من اتفاقية التأجير",
              t25:"أبعاد المستودع",
              t26:"الحجم (متر)",
              t27:"الطول",
              t28:"العرض",
              t29:"سعة التخزين",
              t30:"متر مربع",
              t31:"الارتفاع",
              t32:"نسخة ممسوحة ضوئيًا من اتفاقية التأجير",
              // t33:"",
              t34:"معلومات مدير المستودع",
              t35:"نوع الهوية",
              t36:"رقم الهوية",
              t37:"تاريخ التعيين",
              t38:"الاسم الأول",
              t39:"اسم العائلة",
              t40:"الاسم الأوسط",
              t41:"اسم الاب",
              t42:"اسم الجد",
              t43:"رقم الهاتف",
              t44:"البريد الإلكتروني",
              t45:"معلومات الضمان البنكي",
              t46:"معلومات الضمان البنكي",
              t47:"معلومات إضافية",
              t48:"١. هل أنت بوضع مالي سليم؟",
              t49:"التعهد",
              t50:"الاسم",
              t51:"الوظيفة",
              t52:"نوع الهوية",
              t53:"رقم الهوية",
              t54:"أوافق",
              t55:"الأحكام والشروط.",
              explain:"اشرح الجواب",
              file:"ارفق الملف",
              b1:"ضمان بنكي",
              b2:"يرجى مراجعة معلومات الضمان البنكي للمتابعة",
              b3:"إلغاء",
              b4:"معلومات الضمان البنكي",
              
            },
            step4:{
              t1:"النوع والمنتج",
              t2:"في هذا القسم، يرجى تقديم معلومات عن الهدف من استخدام المستودع ونوع السلع الإنتقائية ذات الصلة.",
              t3:"الهدف من استخدام المستودع",
              t4:"صالح من",
              t5:"للحصول على رخصة مستودع لمستودع تخزين يجب أن تستوفي جميع الشروط التالية:",
              t6:"١. كمية السلع المحتفظ بها كمتوسط على مدى 12 شهرا أكثر من احدى ما يلي: ",
              t7:"أ. 10000000 لتر من المشروبات الغازية ، مشروبات الطاقة أو المشروبات المحلاة",
              t8:"ب. 1,000,000,000 سيجارة أو وحدات فردية أخرى من منتجات التبغ",
              t9:"ج. 500,000 كجم من منتجات التبغ الأخرى",
              t10:"٢. يجب إزالة ما لا يقل عن 70٪ من السلع الإنتقائية في الموقع من المملكة تحت تعليق الضريبة",
              t11:"٣. يتم منح الإذن لاستخدام الموقع كمستودع للسلع الإنتقائية من قبل مجلس الإدارة ",
              t12:"إذا لم يتم استيفاء أي مما سبق، فإن الهيئة لن تصدر رخصة المستودع.",
              t13:"ما هو نوع السلع الإنتقائية التي سيتم انتاجها او تخزينها في المستودع؟",
              t14:"أقر بأنني أفي بالمتطلبات المذكورة أعلاه",
            },
            step5:{
              t1:"عنوان المستودع",
              t2:"الرجاء إدخال عنوان واصل الخاص بالمستودع",
              t3:"اسم مستودع (لسهولة التعرف عليه فقط)",
              t4:"يسمح فقط الحروف الهجائية",
              t5:"رقم المبنى",
              t6:"يسمح فقط بالأرقام",
              t7:"15 رقم كحد أقصى",
              t8:"الشارع",
              t9:"الحد الأقصى المسموح به هو 40 أبجديًا رقميًا",
              t10:"المنطقة",
              t11:"المدينة",
              t12:"الرمز البريدي",
              t13:"يسمح فقط بالأرقام",
              t14:"5 أرقام كحد أقصى ",
              t15:"رقم اضافي",
              t16:"10 رقم كحد أقصى",
              t17:"يسمح فقط بالأرقام",
              t18:"الحي",
              t19:"الحد الأقصى المسموح به هو 40 أبجديًا رقميًا",
              t20:"يسمح فقط بالأرقام",
              t21:"خط العرض ",
              t22:"يسمح فقط بالأرقام",
              t23:"15 رقم كحد أقصى",
              t24:"90 الحد الأقصى المسموح به",
              t25:"خط الطول",
              t26:"يسمح فقط بالأرقام",
              t27:"15 رقم كحد أقصى",
              t28:"الحد الأقصى المسموح به 180",
              t29:"يسمح بحد أقصى 40 حرفًا"
            },
            step6:{
              t1:"ملكية المستودع ",
              t2:"أكمل التفاصيل أدناه",
              t3:"هل انت مستأجر المستودع؟",
              t4:"نوع المالك",
              t5:"نوع الهوية",
              t6:"رقم الهوية",
              t7:"الأرقام فقط مسموح بها",
              t8:"حد أدنى 8 أرقام",
              t9:"16 رقم كحد أقصى",
              t10:"جنسية المالك",
              t11:"اسم المالك",
              t12:"رقم الهاتف",
              t13:"الأرقام فقط مسموح بها",
              t14:"9 أرقام كحد أدنى",
              t15:"14 أرقام كحد أقصى",
              t16:"البريد الإلكتروني",
              t17:"الرجاء إدخال عنوان بريد إلكتروني صالح",
              t18:"الرجاء ارفاق نسخة من عقد الإيجار.",
              t19:"رقم السجل التجاري",
              t20:"الأرقام فقط مسموح بها",
              t21:"9 أرقام كحد أدنى",
              t22:"14 رقم كحد أقصى",
              t23:"الرقم المميز",
              t24:"الأرقام فقط مسموح بها",
              t25:"8 أرقام كحد أدنى",
              t26:"16 رقم كحد أقصى",
              t27:"اسم الشركة",
              t28:"يسمح فقط الحروف الهجائية",
              t29:"العنوان",
              t30:"رقم الهاتف",
              t31:"الأرقام فقط مسموح بها",
              t32:"10 أرقام كحد أدنى",
              t33:"14 أرقام كحد أقصى",
              t34:"يرجى ارفاق نسخة من عقد الايجار",
              t35:"تاريخ بداية عقد الايجار",
              t36:"تاريخ نهاية عقد الايجار",
              t37:"الرجاء تحديد نوع المالك",
              t38:"يرجى تحديد نوع الهوية",
              t39:"يسمح فقط بـ 40 حرفًا"
              // t37:"",
            },
            step7:{
              t1:"أبعاد المستودع",
              t2:"يرجى تقديم أبعاد المستودع ",
              t3:"الحجم (متر)",
              t4:"الطول",
              t5:"الأرقام فقط مسموح بها",
              t6:"0.5 كحد أدنى",
              t7:"1000 كحد أقصى",
              t8:"العرض",
              t9:"الأرقام فقط مسموح بها",
              t10:"0.5 كحد أدنى",
              t11:"1000 كحد أقصى",
              t12:"الارتفاع",
              t13:"الأرقام فقط مسموح بها",
              t14:"0.5 كحد أدنى",
              t15:"1000 كحد أقصى",
              t16:"سعة التخزين",
              t17:"متر مكعب",
              t18:"الأرقام فقط مسموح بها",
              t19:"0.5 كحد أدنى",
              t20:"1000 كحد أقصى",
              t21:"متر مربع",
              t22:"الأرقام فقط مسموح بها",
              t23:"0.5 كحد أدنى",
              t24:"1000 كحد أقصى",
              t25:" الحصول عليها من البلدية أو الشؤون المدنية.الرجاء إرفاق نسخة من رخصة البلدية", 
              // t26:"يجب أن تكون المعلومات الواردة أعلاه متطابقة مع وثيقة الأبعاد التي يتم",
              t26:"يجب أن تكون المعلومات الواردة أعلاه متطابقة مع وثيقة الأبعاد التي يتم الحصول عليها من البلدية أو الشؤون المدنية.الرجاء إرفاق نسخة من رخصة البلدية",
            },
            step8:{
              t1:"معلومات مدير المستودع",
              t2:"أكمل التفاصيل أدناه",
              t3:"نوع الهوية",
              t4:"رقم الهوية",
              t5:"الأرقام فقط مسموح بها",
              t6:"8 أرقام كحد أدنى",
              t7:"16 رقم كحد أقصى",
              t8:"جنسية المالك",
              t9:"تاريخ التوظيف ",
              t10:"اللقب",
              t11:"الاسم الأول",
              t12:"اسم العائلة",
              t13:"الاسم الأوسط",
              t14:"اسم الاب",
              t15:"اسم الجد",
              t16:"رقم الجوال",
              t17:"الأرقام فقط مسموح بها",
              t18:"حد أدنى 9 أرقام",
              t19:"14 رقم كحد أقصى",
              t20:"البريد الإلكتروني",
              t21:"يرجى تحديد نوع الهوية",
              t22: {
                t1: "رقم الهوية",
                t2: "تاريخ الميلاد",
                btn1: "التحقق من الهوية",
              },
              t23: "يجب إدخال تاريخ الميلاد"
            },
            step9:{
              t1:"معلومات الضمان البنكي",
              t2:'في هذا القسم الرجاء توفير معلومات الضمان البنكي، و" القيمة الاجمالية لسعر البيع" للأقسام المختلفة سيقوم النظام باحتساب " قيمة الضمان البنكي المبدئي"، و القيمة الإجمالية لسعر البيع* شاملا مبلغ الضريبة.',
              t3:"يرجى تقديم المعدل الشهري للكمية المتوقعة للمستودع لسنة واحدة على الأقل.",
              t4:"يجب أن تكون منتجات التبغ في مستودع مستقل (منتجات التبغ لا يمكن انتاجها أو تخزينها مع المشروبات الغازية,مشروبات الطاقة او المشروبات المحلاة )",
              t5:"يرجى تقديم نسخة ورقية من الضمان البنكي للهيئة بمجرد قبول طلبك.",
              t6:"القيمة الإجمالية لسعر البيع بالتجزئة شامل الضريبة الإنتقائية هو مجموع قيم سعر البيع بالتجزئة للسلع المخزنة، المنقولة والمفرج عنها.",
              t7:"سعر البيع بالتجزئة",
              t8:"النوع",
              t9:"نوع السلع",
              t10:"الكمية",
              t11:"وحدة القياس",
              t12:"إجمالي سعر البيع بالتجزئة",
              t13:"قيمة الضمان البنكي المبدئي",
              t14:"يرجى تقديم خطاب الضمان المصرفي من البنك الذي تتعامل معه والذي يجب أن يكون قابلاً للاسترداد إذا تم تقديمه إلى البنك",
              t15:"نطاق القيمة المسموح بها هو من 0 إلى 999,999,999,999.99 ",
              t16:"يسمح بـ 25 رقماً  كحد أقصى"
            },
            step10:{
              t1:"معلومات إضافية",
              t2:"يرجى تقديم المعلومات الإضافية التالية.",
              t3:"١. هل أنت بوضع مالي سليم؟ ",
              t4:"اشرح الجواب",
              t5:"٢. هل تمت إدانتك أو إدانة الممثل النظامي في إدارة المنشأة التي تزاول من خلالها نشاطك بجريمة مالية ولم يتم رد الإعتبار؟",
              t6:"اشرح الجواب",
              t7:"٣. هل يتوفر لديك نظام إداري يمكن من خلاله إدارة المستودع الضريبي بامتثال وفقاً لأحكام النظام واللائحة؟",
              t8:"اشرح الجواب",
              t9:"٤. هل جوانب الأمن والسلامة لديك كافية للحد من الحوادث وفقاً لما تحدده الجهات المختصه؟",
              t10:"اشرح الجواب",
            },
            step11:{
              t1:"التعهد",
              t11:"أكمل التفاصيل أدناه",
              t2:"الاسم",
              t3:"الوظيفة",
              t4:"نوع الهوية",
              t5:"رقم الهوية",
              t6:"الأرقام فقط مسموح بها",
              t61:"8 أرقام كحد أدنى",
              t7:"16 رقم كحد أقصى",
              t8:"التاريخ",
              t9:"أتعهد أنا الموقع أدناه بأن جميع المعلومات الواردة في هذا الطلب صحيحة ومطابقة للواقع وأني مخوّل حسب الأنظمة لاستكمال هذا الطلب",
              t10:"يسمح فقط بـ 40 حرفًا",
              t12:"يسمح فقط الحروف الهجائية",
            },
            step12:{
                t1:"ملخص",
                t2:"راجع المعلومات أدناه",
                s1:{
                  t1:"مستودع",
                  t2:"الرقم الضريبي",
                  t3:"اسم المنشأة",
                  t4:"الغرض من استخدام المستودع",
                  t5:"تاريخ الإنتهاء",
                  t6:"هل تريد تمديد صلاحية فترة التجديد لأكثر من سنة؟",
                  t7:"حدد الفترة التي تريد زيادة الصلاحية؟",
                },
                s2:{
                  t1:"النوع والمنتج",
                  t2:"الهدف من استخدام المستودع",
                  t3:"ما هو نوع السلع الإنتقائية التي سيتم انتاجها او تخزينها في المستودع؟",
                },
                s3:{
                  t1:"عنوان المستودع",
                  t2:"الرجاء إدخال عنوان واصل الخاص بالمستودع",
                  t3:"اسم المبنى",
                  t4:"الشارع",
                  t5:"المنطقة",
                  t6:"المدينة",
                  t7:"الرمز البريدي",
                  t8:"رقم العنوان",
                  t9:"الحي",
                  t10:"خط العرض",
                  t11:"خط الطول",
                },
                s4:{
                  t1:"ملكية المستودع",
                  t2:"هل انت مستأجر المستودع؟",
                  t3:"نوع الهوية",
                  t4:"رقم الهوية",
                  t5:"جنسية المالك",
                  t6:"اسم المالك",
                  t7:"رقم الجوال",
                  t8:"البريد الإلكتروني",
                  t9:"رقم السجل التجاري",
                  t10:"الرقم المميز",
                  t11:"اسم الشركة",
                  t12:"العنوان",
                  t13:"رقم الجوال",
                  t14:"نسخة ممسوحة ضوئيًا من اتفاقية التأجير",
                },
                s5:{
                  t1:"أبعاد المستودع",
                  t2:"الحجم (متر)",
                  t21:"الطول",
                  t3:"العرض",
                  t4:"سعة التخزين",
                  t5:"متر مكعب",
                  t6:"متر مربع",
                  t7:"الارتفاع",
                  t8:"نسخة ممسوحة ضوئيًا من اتفاقية التأجير", 
                },
                s6:{
                  t1:"معلومات مدير المستودع",
                  t2:"نوع الهوية",
                  t3:"رقم الهوية",
                  t4:"جنسية المالك",
                  t5:"اللقب",
                  t6:"الاسم الأول",
                  t7:"اسم العائلة",
                  t8:"الاسم الأوسط",
                  t9:"اسم الاب",
                  t10:"اسم الجد",
                  t11:"رقم الهاتف",
                  t12:"البريد الإلكتروني",
                },
                s7:{
                  t1:"معلومات الضمان البنكي",
                  t2:"معلومات الضمان البنكي",
                  t3:"ريال سعودي",
                },
                s8:{
                  t1:"معلومات إضافية",
                  t2:"١. هل أنت بوضع مالي سليم؟",
                  t3:"ارفق الملف",
                  t4:"اشرح الجواب",
                  t5:"هل تمت إدانتك أو إدانة الممثل النظامي في إدارة المنشأة التي تزاول من خلالها نشاطك بجريمة مالية ولم يتم رد الإعتبار؟",
                  t6:"ارفق الملف",
                  t7:"اشرح الجواب",
                  t8:"هل يتوفر لديك نظام إداري يمكن من خلاله إدارة المستودع الضريبي بامتثال وفقاً لأحكام النظام واللائحة؟",
                  t9:"ارفق الملف",
                  t10:"اشرح الجواب",
                  t11:"هل جوانب الأمن والسلامة لديك كافية للحد من الحوادث وفقاً لما تحدده الجهات المختصه؟",
                  t12:"ارفق الملف",
                  t13:"اشرح الجواب",
                },
                s9:{
                  t1:"التعهد",
                  t2:"الاسم",
                  t3:"الوظيفة",
                  t4:"نوع الهوية",
                  t5:"رقم الهوية",
                  t6:"أوافق",
                  t7:"الأحكام والشروط.",
                }
            },
            step13:{
              t1:"الإشعار",
              t2:"تقر الهيئة باستلام نموذج طلب تجديد رخصة مستودع ضريبي ",
              t3:"الرقم المرجعي",
              t4:"التاريخ",
              t5:"يرجى الاحتفاظ بالرقم المرجعي لهذا الطلب وفي حال وجود أي استفسار يمكنك استخدام هذا الرقم المرجعي. سوف تقوم الهيئة بتقييم الطلب والرد عليكم وفي حالة نقص في البيانات سوف تعاود الهيئة الاتصال بك. لمزيد من المعلومات يمكنك زيارة فرع الهيئة.",
              t6:"الإشعار",
              t7:"تحميل النموذج",
            },
            termsConditions:{​​​​​​​
                      t1:"الشروط والأحكام :",
                      t2:"يجب إكمال هذا النموذج من قبل الممثل القانوني للكيان ، وسيتم تطبيق العقوبات المنصوص عليها في لائحة الهيئة العامة للزكاة والدخل إذا كانت المعلومات المقدمة في النموذج غير صحيحة دون المساس بالعقوبات المنصوص عليها في اللوائح الأخرى المعمول بها في المملكة.",
                      t3:".يجب أن يكون تأسيس المنشأة وفقاً للأنظمة المطبقة بالمملكة.",
                      t4:". يجب على المنشاة امساك دفاتر وحسابات منتظمة وفقاً لأنظمة الهيئة",
                      t5:".للهيئة الحق في الحصول على البيانات المالية والسجلات المحاسبية للمنشأة ومراجعتها",
                      t6:".للهيئة الحق في الحصول على البيانات المالية والسجلات المحاسبية للمالك (الملاك) ومراجعتها",
                      t7:".يجب دفع الرسوم المقررة بموجب أنظمة الهيئة",
                      t8:".يجب على المنشأة إبلاغ الهيئة بأي تغيير جوهري يتعلق بالمستودع الضريبي وفقاً للأحكام والإجراءات المنصوص عليها في بموجب أنظمة الهيئة",
                      t9:".تستثنى المنشئات القائمة قبل صدور نظام الضريبة الإنتقائية من تعبئة الفقرات (9-10-12-13) من هذا النموذج، لأغراض الترخيص وتطبق على القضايا التي تنشأ بعد صدوره",
                      t10:".قد يتم تعليق أو إلغاء هذا الترخيص وفقاً للحالات المنصوص عليها بموجب أنظمة الهيئة",
                      dashboard:"الذهاب إلى لوحة التحكم",
                    }​​​​​​​
            
          },

        zacatcit:{
          p1:"بحث",
          c1:{
            t1:"الرقم المرجعي",
            t2:"تاريخ الاستحقاق"
          }
  
        }
  
      },
    },
  };
  