export const nonRegTPConstants = {
    langz: {
      eng: {
        dir: "ltr",
        consortium: {
          title: "Non-Regular Taxpayer",
          header: {
            h1: "Organization Type",
            h2: "Complete Information",
            h3: "Password",
          },
          c1: {
            title: "Organization Information",
            in1: "Name of the Business\Company\Entity",
            in2: "GCC ID",
            in3: "Commercial Registration Number",
            in4: "Attachment",
            in5: "Company Business Descripation",
            in6: "Copy Of CR",
          },
          c2: {
            title: "Address in GCC State",
            in1: "Country",
            in2: "City",
            in3: "Street Name",
            in4: "House Number",
            in5: "P.O.Box",
            in6: "Postal Code",
            in7: "Phone Number",
            in8: "Company Website"
          },
          c3: {
            title: "Representative Information",
            in1:"Position and Designation",
            in2: "ID Type",
            in3: "ID Number",
            in4: "Name",
            in5: "Nationality",
            in6: "Mobile",
            in7: "Email",
            in8: "Confirm Email",
            in9: "Copy of ID",
            in10: "Date of Birth",
          },         
          err: {
            nameBCEReq:"Name of the Business\Company\Entity is Required",
            nameBCELen:"Name of the Business\Company\Entity should be maximum of 120 characters",
            gccIDMinlength: "Invalid entry",
            enterCRNumber: "Please enter CR number",
            copyOfCRRequired: "Please add attachment",
            enterGccID: "Enter GCC ID",
            enterDesc:"Company Business Descripation is Required",
            in1: "is Required",
            in2: "should be atleast 10 characters long",
            in3: "can be atmax 10 characters long!",
            in4: "must be Numeric",
            in5: "is Invalid",
            in6: "Email and Confirm Email should be same",
            in7: "should start with 7",
            in8: "should start with 3",
            in9: "should start with 1",
            in10: "should start with 2",
            in11: "should be between 7-15 digits",
            in12: "should be 10 digits",
            in13: "should start with 5",
            in14: "should be atleast 9 characters long",
            invalidcompanyID: "",
            enterCompanyName: "Enter Company Name",
            containsOnlyNumbers: "Only numbers not allowed for Company name",
            containsSpecialChars: "Special characters are not allowed in Company Name",
            enterEmail: "Please enter email-id",
            enterConfirmEmail: "Please enter email-id",
            emailinvalid: "Invalid Email address",
            emailsNotMatch: "Email and Confirm Email should be same",
            companyidlength: "Company ID should be 10 digit",
            companyidstartwitherr: "Company ID should start with 7",
            mobilenumbererr: "Mobile Number should start with 5",
            maxLimit: "Maximum limit to attach files reached",
            branchNamerequired: "Enter Branch Name",
            copyofmemorequired: "Please attach copy of Company Memorandum for Outlet Number ",
            mgarqrd: "Please choose main group activity",
            sgarqrd: "Please choose sub group activity",
            marqrd: "Please choose main activity",
            countryrqrd: "Select Country",
            nationalityrqrd: "Select Nationality",
            provincerqrd: "Select Province",
            cityrqrd: "Select City",
            countquarterrqrd: "Enter Quarter",
            streetrqrd: "Enter Street",
            bnorqrd: "Enter House number",
            ziprqrd: "Enter Postal Code",
            unorqrd: "Enter P.O.Box Number",
            companyTinErr: "Contact person should be an Individual and not a company",
            invalidCR: "Invalid CR",
            enterValidFromDate: "Enter Valid From Date",
            enterLicenseNumber: "Enter License Number",
            enterContractNumber: "Please enter contact number",
            selectIssueBy: "Please Select Issue By",
            selectIssueCountry: "Please select Country",
            selectIssueCity: "Please select City",
            copyOfLicenseRequired: "Please add attachment",
            copyOfContractRequired: "Please add attachment",
            copyOfGMIDRequired: "Please add attachment",
            addAttachment: "Please add attachment",
            fileSizeError: "File size should be less than 5 MB",
            fileTypeError: "Choose only file with extension DOC, DOCX, XLS, XLSX, PDF, JPG",
            nationalIDStartWith: "ID number should start with 1",
            nationalIDMinLength: "National ID should be 10 digits",
            iqamaIDStartWith: "ID number should start with 2",
            iqamaIDMinLength: "IQAMA ID should be 10 digits",
            enterDateOfBirth: "Please enter date of birth",
            enterStartDate: "Enter Start Date",
            enterNationalID: "Enter National ID",
            enterIqamaID: "Enter Iqama ID",
            enterIssueCountryPassport: "Please select issue country",
            enterPassportNumber: "Please enter passport number",
            tinNumberMinlength: "Tin Number should be atleast 10 characters long",
            tinNumberStartWith: "يجب أن يبدأ الرقم الخاص بالرقم 3",
            selectIDType: "Select ID Type",
            enterFirstName: "Please Enter First Name",
            enterLastName: "Please Enter Last Name",
            enterMobileNumber: "Please Enter Mobile Number",
            enterPhoneNumber: "Please Enter Phone Number",
            startsWithZero: "Mobile Number should not start with 0",
            bcpMobileNumberStartWith: "Mobile Number should be start with 009665",
            bcpMobileNumberMaxLength: "Mobile Number should be 14 digits",
            enterIDNumber: "Enter ID Number",
            dobFutureDate: "Date of Birth can not be greater than current date",
            startDateFutureDate: "Start Date can not be greater than current date",
            scstdtfutureDate: "Share Capital Start Date cannot be greater than current date",
            spstdtfutureDate: "Share Profit Start Date cannot be greater than current date",
            validFromFutureDate: "Valid From cannot be greater than current date",
            copyOfPassport: "Copy Of General Manger ID",
            copyOfText: "Copy of ",
            tinInYourCountryAlert: "If you are GCC resident please select GCC ID. Selecting Tin in your country will make shareholder liable for income tax"
          },         
          back: "Back",
          continue: "Continue",
          yes: "YES",
          no: "NO",
          ok: "OK",
          confirm: "Confirmation",
          cancel: "Cancel",
          acknowledgement: {
            title: "Acknowledgement",
            message: "GAZT acknowledges the receipt of your registration application",
            info: {
              name: "Name",
              appno: "Application Number",
              date: "Date",
              login_link_label: "Go To Login"
            }
          },        
          attachments: {
            label1: "Drag and drop file to upload documentation",
            label2: "File size should be less than 10 MB.",
            txt1: "1. The maximum number of attachments that can be uploaded is 5",
            txt2: "2. Alert, you must adjust the settings of the scanner so that the zip file size is less than 10MB",
            txt3: "3. The recommended settings for your scanner is : 1024 745",
            txt4: "4. Choose only file with extension DOC, DOCX, XLS, XLSX, PDF, JPG",
            txt5: "5. Please make sure that the attached file is free of any viruses or hacking programs as any file containing this type of file will be rejected automatically.",
          },
         
          idTypes: [
            {
              name: "National ID",
              value: "ZS0001",
            },
            { name: "Iqama ID", value: "ZS0002" },
            { name: "GCC ID", value: "ZS0003" },
           
          ],
         
        }, 
        idTypes: [
          {
            name: "National ID",
            value: "ZS0001",
          },
          { name: "Iqama ID", value: "ZS0002" },
          { name: "GCC ID", value: "ZS0003" },
          { name: "Passport", value: "FS0002" },
        ],
        
  
      },
      arb: {
        dir: "rtl",
        consortium: {
          title: "Non-Regular Taxpayer",
          header: {
            h1: "Organization Type",
            h2: "إكمال البيانات",
            h3: "كلمة المرور",
          },
          c1: {
            title: "معلومات المنظمة",
            in1: "الرقم المميز",
            in2: "هوية خليجية",
            in3: "رقم السجل التجاري",
            in4: "المرفق",
            in5: "Company Business Descripation",
            in6: "نسخة من السجل التجاري",
          },
          c2: {
            title: "Address in GCC State",
            in1: "Country",
            in2: "City",
            in3: "Street Name",
            in4: "House Number",
            in5: "P.O.Box",
            in6: "Postal Code",
            in7: "Mobile Number",
            in8: "Company Website"
          },
          c3: {
            title: "Representative Information",
            in1:"Position and Designation",
            in2: "ID Type",
            in3: "ID Number",
            in4: "Name",
            in5: "Nationality",
            in6: "Mobile",
            in7: "Email",
            in8: "Confirm Email",
            in9: "Copy of ID",
            in10: "Date of Birth",
          },  
          err: {
            nameBCEReq:"Name of the Business\Company\Entity is Required",
            nameBCELen:"Name of the Business\Company\Entity should be maximum of 120 characters",          
            gccIDMinlength: "إدخال غير صالح",
            enterContractNumber: "الرجاء ادخال رقم العقد",
            copyOfCRRequired: "من فضلك ارفق نسخة من السجل التجاري للفرع الرئيسي/الفرعي ذا علاقة بالترخيص",
            enterGccID: "Enter GCC ID",
            enterDesc:"Company Business Descripation is Required",

            in1: "مطلوب",
            in2: "should be atleast 10 characters long",
            in3: "can be atmax 10 characters long!",
            in4: "must be Numeric",
            in5: "is Invalid",
            in6: "البريد الإلكتروني المدخل غير مطابق, الرجاء ادخال بريد صحيح",
            in7: "should start with 7",
            in8: "should start with 3",
            in9: "should start with 1",
            in10: "should start with 2",
            in11: "should be between 7-15 digits",
            in12: "should be 10 digits",
            in13: "should start with 5",
            in14: "should be atleast 9 characters long",
            invalidcompanyID: " رقم الشركة يجب أن يتكون من 10 أرقام",
            enterCompanyName: "الرجاء ادخال اسم الشركة",
            containsOnlyNumbers: "اسم الشركة يجب أن يحتوي على أحرف فقط",
            containsSpecialChars: "اسم الشركة يجب أن لايحتوي على رموز",
            enterEmail: "الرجاء ادخال البريد الإلكتروني",
            enterConfirmEmail: "الرجاء ادخال البريد الإلكتروني",
            emailinvalid: "الرجاء إدخال بريد إلكتروني صحيح",
            emailsNotMatch: "البريد الإلكتروني المدخل غير مطابق, الرجاء ادخال بريد صحيح",
            companyidlength: "رقم الشركة يجب أن يتكون من 10 أرقام",
            companyidstartwitherr: "رقم الشركة يجب ان يبدا بـرقم 7",
            mobilenumbererr: "يجب أن يبدأ رقم الهاتف المحمول بالرقم خمسة",
            maxLimit: "Maximum limit to attach files reached",
            branchNamerequired: "ادخل اسم الفرع",
            copyofmemorequired: "الرجاء إرفاق نسخة من عقد تأسيس المنشأة للفرع رقم ",
            mgarqrd: "الرجاء اختيار المجموعة الرئيسية",
            sgarqrd: "الرجاء اختيار المجموعة الفرعية",
            marqrd: "الرجاء اختيار النشاط الرئيسي",
            countryrqrd: "اختر الدولة",
            nationalityrqrd:"اختر الدولة",
            provincerqrd: "اختر المنطقة",
            cityrqrd: "اختر المدينة",
            quarterrqrd: "ادخل الحي",
            streetrqrd: "ادخل اسم الشارع",
            bnorqrd: "ادخل رقم المبنى",
            ziprqrd: "ادخل الرمز البريدي",
            unorqrd: "الرجاء إدخال رقم الوحدة",
            companyTinErr: "شخص الاتصال يجب ان يكون فرد وليس شركة",
            enterCRNumber: "الرجاء ادخال رقم السجل التجاري",
            invalidCR: "رقم السجل التجاري غير صحيح",
            enterValidFromDate: "ادخل تاريخ بدء صحيح",
            enterLicenseNumber: "ادخل رقم الرخصة",
            // enterContractNumber: "ادخل رقم الرخصة",
            selectIssueBy: "الرجاء اختيار جهة الإصدار",
            selectIssueCountry: "الرجاء اختيار دولة الإصدار",
            selectIssueCity: "الرجاء اختيار المدينة",
            copyOfLicenseRequired: "الرجاء رفع المرفقات",
            copyOfContractRequired: "الرجاء رفع المرفقات",
            copyOfGMIDRequired: "الرجاء رفع المرفقات",
            addAttachment: "الرجاء رفع المرفقات",
            fileSizeError: "يجب ان يكون حجم الملف المرفق اقل من 5 ميجا",
            fileTypeError: "الرجاء إختيار ملف من الإمتدادات التالية فقط DOC, DOCX, XLS, XLSX, PDF, JPG",
            nationalIDStartWith: "رقم الهوية الوطنية يجب أن يبدأ برقم 1",
            nationalIDMinLength: "رقم الهوية الوطنية يجب ان يتكون من 10 أرقام",
            iqamaIDStartWith: "رقم الهوية غير صحيح",
            iqamaIDMinLength: "رقم الإقامة يجب أن يتكون من 10 أرقام",
            enterDateOfBirth: "الرجاء إدخال تاريخ الميلاد",
            enterStartDate: "ادخل تاريخ البدء",
            enterNationalID: "Enter National ID",
            enterIqamaID: "Enter Iqama ID",
            enterIssueCountryPassport: "الرجاء اختيار دولة الإصدار",
            enterPassportNumber: "الرجاء إدخال رقم الجواز",
            tinNumberMinlength: "Tin Number should be atleast 10 characters long",
            tinNumberStartWith: "يجب أن يبدأ الرقم بالرقم 3",
            selectIDType: "Select ID Type",
            enterFirstName: "الرجاء إدخال الاسم الأول",
            enterLastName: "الرجاء إدخال الاسم الأخير",
            enterMobileNumber: "الرجاء ادخال رقم الجوال",
            enterPhoneNumber: "الرجاء ادخال رقم الجوال",
            startsWithZero: "رقم الهاتف المحمول يجب أن لا يبدأ بصفر",
            bcpMobileNumberStartWith: "يجب ان يبدأ رقم الهاتف الجوال بـ 009665",
            bcpMobileNumberMaxLength: "رقم الجوال خاطئ يجب أن يتكون من 14 رقم",
            enterIDNumber: "ادخل رقم الهوية",
            dobFutureDate: "تاريخ الميلاد المدخل يجب ان يكون اقدم من تاريخ الحالي",
            startDateFutureDate: "Start Date can not be greater than current date",
            scstdtfutureDate: "Share Capital Start Date cannot be greater than current date",
            spstdtfutureDate: "Share Profit Start Date cannot be greater than current date",
            validFromFutureDate: "Valid From cannot be greater than current date",
            copyOfPassport: "نسخة من جواز السفر",
            copyOfText: " نسخة من ",
            tinInYourCountryAlert: "اذا كنت خليجي الرجاء اختر نوع هوية المواطن الخليجي, اذا تم اختيار الرقم الضريبي في البلد الام فسيتم محاسبتك ضريباً وليس زكوياً"
          },
         
          back: "رجوع",
          continue: "متابعة",
          yes: "نعم",
          no: "لا",
          ok: "موافق",
          confirm: "تأكيد",
          cancel: "إلغاء",
          acknowledgement: {
            title: "إشعار إستلام",
            message: "تقر الهيئة العامة للزكاة والدخل باستلام طلب التسجيل الخاص بك",
            info: {
              name: "الاسم",
              appno: "رقم الطلب",
              date: "التاريخ",
              login_link_label: "الذهاب لصفحة الدخول"
            }
          },
          attachments: {
            label1: "إسحب وأسقط ملف لتحميل الوثائق",
            label2: "بأقصى حجم 10 ميجا بايت",
            txt1: "1.يجب ان لا يتجاوز عدد المرفقات لعملية تقديم طلب التسجيل عن 5 مرفقات. ",
            txt2: "2.تنبيه, يجب ضبط اعدادات الماسح الضوئي بحيث يكون حجم الملف المضغوط أقل من. 10MB",
            txt3: "3.الاعدادات الموصى بها للماسح الضوئي هي: 1024 745",
            txt4: "4.الرجاء إرفاق ملف من الامتدادت التالية فقط DOC, DOCX, XLS, XLSX, PDF, JPG",
            txt5: "5.يرجى التأكد من خلو الملف المرفق من أي فيروسات أو برامج اختراق حيث سيتم رفض أي ملف يحتوي على هذا النوع من الملفات بشكل آلي."
          },
         
          idTypes: [
            {
              name: "هوية وطنية",
              value: "ZS0001",
            },
            { name: "هوية مقيم", value: "ZS0002" },
            { name: "هوية خليجية", value: "ZS0003" },
          ]
        },
        idTypes: [
          {
            name: "هوية وطنية",
            value: "ZS0001",
          },
          { name: "هوية مقيم", value: "ZS0002" },
          { name: "هوية خليجية", value: "ZS0003" },
          { name: "رقم الجواز", value: "FS0002" },
        ]
      },
    },
  };
  