export const fdConstants = {
  langz: {
    eng: {
      dir: "ltr",
      financialDetails: {               
        c5: {
          title: "Financial Details",
          in1: "Account Method",
          in2: "TIN in your country",
          in3: "TAN in your country",
          in4: "Capital Registration Date",
          in5: "Capital Amount(SAR)",
          in6: "End of Financial",
          in7: "Day",
          in8: "Month",
          in9: "Business Commencement Date",
          in10: "Taxable Date",
          label1: "Calendar Type to select the End of financial year ?",
          label2: "Hijri",
          label3: "Gregorian",
        },
        err: {
          in1: "is Required",
          in2: "should be atleast 10 characters long",
          // in3: "can be atmax 10 characters long!",
          // in4: "must be Numeric",
          // in5: "is Invalid",
          in6: "Email and Confirm Email should be same",
          // in7: "should start with 7",
          in8: "should start with 3",
          in9: "should start with 1",
          in10: "should start with 2",
          in11: "should be between 7-15 digits",
          in12: "should be 10 digits",
          // in13: "should start with 5",
          // in14: "should be atleast 9 characters long",
          invalidcompanyID: "",
          enterCompanyName: "Enter Company Name",
          containsOnlyNumbers: "Only numbers not allowed for Company name",
          containsSpecialChars: "Special characters are not allowed in Company Name",
          enterEmail: "Please enter email-id",
          enterConfirmEmail: "Please enter email-id",
          emailinvalid: "Invalid Email address",
          emailsNotMatch: "Email and Confirm Email should be same",
          companyidlength: "Company ID should be 10 digit",
          companyidstartwitherr: "Company ID should start with 7",
          mobilenumbererr: "Mobile Number should start with 5",
          // maxLimit: "Maximum limit to attach files reached",
          branchNamerequired: "Enter Branch Name",
          copyofmemorequired: "Please attach copy of Company Memorandum for Outlet Number ",
          mgarqrd: "Please choose main group activity",
          sgarqrd: "Please choose sub group activity",
          marqrd: "Please choose main activity",
          countryrqrd: "Select Country",
          provincerqrd: "Select Province",
          cityrqrd: "Select City",
          countquarterrqrd: "Enter Quarter",
          streetrqrd: "Enter Street",
          bnorqrd: "Enter Building number",
          ziprqrd: "Enter Postal Code",
          unorqrd: "Enter Unit Number",
          companyTinErr: "Contact person should be an Individual and not a company",
          enterCRNumber: "Please enter CR number",
          invalidCR: "Invalid CR",
          enterValidFromDate: "Enter Valid From Date",
          enterLicenseNumber: "Enter License Number",
          enterContractNumber: "Please enter contract number",
          selectIssueBy: "Please Select Issue By",
          selectIssueCountry: "Please select Country",
          selectIssueCity: "Please select City",
          copyOfCRRequired: "Please add attachment",
          copyOfLicenseRequired: "Please add attachment",
          copyOfContractRequired: "Please add attachment",
          copyOfGMIDRequired: "Please add attachment",
          addAttachment: "Please add attachment",
          fileSizeError: "File size should be less than 5 MB",
          fileTypeError: "Choose only file with extension DOC, DOCX, XLS, XLSX, PDF, JPG",
          nationalIDStartWith: "ID number should start with 1",
          nationalIDMinLength: "National ID should be 10 digits",
          iqamaIDStartWith: "ID number should start with 2",
          iqamaIDMinLength: "IQAMA ID should be 10 digits",
          gccIDMinlength: "GCC ID should be between 7-15 digits",
          enterDateOfBirth: "Please enter date of birth",
          enterStartDate: "Enter Start Date",
          enterNationalID: "Enter National ID",
          enterIqamaID: "Enter Iqama ID",
          enterGccID: "Enter GCC ID",
          enterIssueCountryPassport: "Please select issue country",
          enterPassportNumber: "Please enter passport number",
          tinNumberMinlength: "Tin Number should be atleast 10 characters long",
          tinNumberStartWith: "يجب أن يبدأ الرقم الخاص بالرقم 3",
          selectIDType: "Select ID Type",
          enterFirstName: "Please Enter First Name",
          enterLastName: "Please Enter Last Name",
          enterMobileNumber: "Please Enter Mobile Number",
          startsWithZero: "Mobile Number should not start with 0",
          bcpMobileNumberStartWith: "Mobile Number should be start with 009665",
          bcpMobileNumberMaxLength: "Mobile Number should be 14 digits",
          enterIDNumber: "Enter ID Number",
          dobFutureDate: "Date of Birth can not be greater than current date",
          startDateFutureDate: "Start Date can not be greater than current date",
          scstdtfutureDate: "Share Capital Start Date cannot be greater than current date",
          spstdtfutureDate: "Share Profit Start Date cannot be greater than current date",
          validFromFutureDate: "Valid From cannot be greater than current date",
          copyOfPassport: "Copy Of General Manger ID",
          copyOfText: "Copy of ",
          tinInYourCountryAlert: "If you are GCC resident please select GCC ID. Selecting Tin in your country will make shareholder liable for income tax",
          selectAnyOne:"Select any one"
        },
        back: "Back",
        continue: "Continue",
        yes: "YES",
        no: "NO",
        ok: "OK",
        confirm: "Confirmation",
        cancel: "Cancel",        
        error:"Error",
        accounting: "Accounting method",
        estimated: "Estimated method",        
        days: [
          { key: '01', value: '01' }, { key: '02', value: '02' }, { key: '03', value: '03' }, { key: '04', value: '04' }, { key: '05', value: '05' },
          { key: '06', value: '06' }, { key: '07', value: '07' }, { key: '08', value: '08' }, { key: '09', value: '09' }, { key: '10', value: '10' },
          { key: '11', value: '11' }, { key: '12', value: '12' }, { key: '13', value: '13' }, { key: '14', value: '14' }, { key: '15', value: '15' },
          { key: '16', value: '16' }, { key: '17', value: '17' }, { key: '18', value: '18' }, { key: '19', value: '19' }, { key: '20', value: '20' },
          { key: '21', value: '21' }, { key: '22', value: '22' }, { key: '23', value: '23' }, { key: '24', value: '24' }, { key: '25', value: '25' },
          { key: '26', value: '26' }, { key: '27', value: '27' }, { key: '28', value: '28' }, { key: '29', value: '29' }, { key: '30', value: '30' },
          { key: 'LD', value: 'Last Day' }
        ],
        months: [
          { key: '01', value: '1' }, { key: '02', value: '2' }, { key: '03', value: '3' }, { key: '04', value: '4' }, { key: '05', value: '5' },
          { key: '06', value: '6' }, { key: '07', value: '7' }, { key: '08', value: '8' }, { key: '09', value: '9' }, { key: '10', value: '10' },
          { key: '11', value: '11' }, { key: '12', value: '12' }
        ]        
      }
    },
    arb: {
      dir: "rtl",
      financialDetails: {        
        c5: {
          title: "التفاصيل المالية",
          in1: "طريقة المحاسبة",
          in2: "الرقم المميز في بلدك",
          in3: "رقم الحساب الضريبي في بلدك",
          in4: "تاريخ تسجيل رأس المال",
          in5: "مبلغ رأس المال (ر.س)",
          in6: "نهاية السنة المالية",
          in7: "يوم",
          in8: "شهر",
          in9: "تاريخ بدء الأعمال",
          in10: "تاريخ الخضوع للضريبة",
          label1: "الرجاء اختيار نوع التقويم لتحديد نهاية السنة المالية؟ ",
          label2: "هجري",
          label3: "ميلادي",
        },
        err: {
          in1: "مطلوب",
          in2: "should be atleast 10 characters long",
          // in3: "can be atmax 10 characters long!",
          // in4: "must be Numeric",
          // in5: "is Invalid",
          in6: "البريد الإلكتروني المدخل غير مطابق, الرجاء ادخال بريد صحيح",
          // in7: "should start with 7",
          in8: "should start with 3",
          in9: "should start with 1",
          in10: "should start with 2",
          in11: "should be between 7-15 digits",
          in12: "should be 10 digits",
          // in13: "should start with 5",
          // in14: "should be atleast 9 characters long",
          invalidcompanyID: " رقم الشركة يجب أن يتكون من 10 أرقام",
          enterCompanyName: "الرجاء ادخال اسم الشركة",
          containsOnlyNumbers: "اسم الشركة يجب أن يحتوي على أحرف فقط",
          containsSpecialChars: "اسم الشركة يجب أن لايحتوي على رموز",
          enterEmail: "الرجاء ادخال البريد الإلكتروني",
          enterConfirmEmail: "الرجاء ادخال البريد الإلكتروني",
          emailinvalid: "الرجاء إدخال بريد إلكتروني صحيح",
          emailsNotMatch: "البريد الإلكتروني المدخل غير مطابق, الرجاء ادخال بريد صحيح",
          companyidlength: "رقم الشركة يجب أن يتكون من 10 أرقام",
          companyidstartwitherr: "رقم الشركة يجب ان يبدا بـرقم 7",
          mobilenumbererr: "يجب أن يبدأ رقم الهاتف المحمول بالرقم خمسة",
          // maxLimit: "Maximum limit to attach files reached",
          branchNamerequired: "ادخل اسم الفرع",
          copyofmemorequired: "الرجاء إرفاق نسخة من عقد تأسيس المنشأة للفرع رقم ",
          mgarqrd: "الرجاء اختيار المجموعة الرئيسية",
          sgarqrd: "الرجاء اختيار المجموعة الفرعية",
          marqrd: "الرجاء اختيار النشاط الرئيسي",
          countryrqrd: "اختر الدولة",
          provincerqrd: "اختر المنطقة",
          cityrqrd: "اختر المدينة",
          quarterrqrd: "ادخل الحي",
          streetrqrd: "ادخل اسم الشارع",
          bnorqrd: "ادخل رقم المبنى",
          ziprqrd: "ادخل الرمز البريدي",
          unorqrd: "الرجاء إدخال رقم الوحدة",
          companyTinErr: "شخص الاتصال يجب ان يكون فرد وليس شركة",
          enterCRNumber: "الرجاء ادخال رقم السجل التجاري",
          invalidCR: "رقم السجل التجاري غير صحيح",
          enterValidFromDate: "ادخل تاريخ بدء صحيح",
          enterLicenseNumber: "ادخل رقم الرخصة",
          // enterContractNumber: "ادخل رقم الرخصة",
          enterContractNumber: "الرجاء ادخال رقم العقد",
          selectIssueBy: "الرجاء اختيار جهة الإصدار",
          selectIssueCountry: "الرجاء اختيار دولة الإصدار",
          selectIssueCity: "الرجاء اختيار المدينة",
          copyOfCRRequired: "من فضلك ارفق نسخة من السجل التجاري للفرع الرئيسي/الفرعي ذا علاقة بالترخيص",
          copyOfLicenseRequired: "الرجاء رفع المرفقات",
          copyOfContractRequired: "الرجاء رفع المرفقات",
          copyOfGMIDRequired: "الرجاء رفع المرفقات",
          addAttachment: "الرجاء رفع المرفقات",
          fileSizeError: "يجب ان يكون حجم الملف المرفق اقل من 5 ميجا",
          fileTypeError: "الرجاء إختيار ملف من الإمتدادات التالية فقط DOC, DOCX, XLS, XLSX, PDF, JPG",
          nationalIDStartWith: "رقم الهوية الوطنية يجب أن يبدأ برقم 1",
          nationalIDMinLength: "رقم الهوية الوطنية يجب ان يتكون من 10 أرقام",
          iqamaIDStartWith: "رقم الهوية غير صحيح",
          iqamaIDMinLength: "رقم الإقامة يجب أن يتكون من 10 أرقام",
          gccIDMinlength: "رقم مواطني دول الخليج يجب ان يتكون من 7 الى 15 رقم",
          enterDateOfBirth: "الرجاء إدخال تاريخ الميلاد",
          enterStartDate: "ادخل تاريخ البدء",
          enterNationalID: "Enter National ID",
          enterIqamaID: "Enter Iqama ID",
          enterGccID: "Enter GCC ID",
          enterIssueCountryPassport: "الرجاء اختيار دولة الإصدار",
          enterPassportNumber: "الرجاء إدخال رقم الجواز",
          tinNumberMinlength: "Tin Number should be atleast 10 characters long",
          tinNumberStartWith: "يجب أن يبدأ الرقم بالرقم 3",
          selectIDType: "Select ID Type",
          enterFirstName: "الرجاء إدخال الاسم الأول",
          enterLastName: "الرجاء إدخال الاسم الأخير",
          enterMobileNumber: "الرجاء ادخال رقم الجوال",
          startsWithZero: "رقم الهاتف المحمول يجب أن لا يبدأ بصفر",
          bcpMobileNumberStartWith: "يجب ان يبدأ رقم الهاتف الجوال بـ 009665",
          bcpMobileNumberMaxLength: "رقم الجوال خاطئ يجب أن يتكون من 14 رقم",
          enterIDNumber: "ادخل رقم الهوية",
          dobFutureDate: "تاريخ الميلاد المدخل يجب ان يكون اقدم من تاريخ الحالي",
          startDateFutureDate: "Start Date can not be greater than current date",
          scstdtfutureDate: "Share Capital Start Date cannot be greater than current date",
          spstdtfutureDate: "Share Profit Start Date cannot be greater than current date",
          validFromFutureDate: "Valid From cannot be greater than current date",
          copyOfPassport: "نسخة من جواز السفر",
          copyOfText: " نسخة من ",
          tinInYourCountryAlert: "اذا كنت خليجي الرجاء اختر نوع هوية المواطن الخليجي, اذا تم اختيار الرقم الضريبي في البلد الام فسيتم محاسبتك ضريباً وليس زكوياً",
          selectAnyOne:"الرجاء تحديد اختيار"
        },        
        back: "رجوع",
        continue: "متابعة",
        yes: "نعم",
        no: "لا",
        ok: "موافق",
        confirm: "تأكيد",
        cancel: "إلغاء",
        error:"خطأ",        
        accounting: "حسابات",
        estimated: "تقديري",              
        days: [
          { key: '01', value: '01' }, { key: '02', value: '02' }, { key: '03', value: '03' }, { key: '04', value: '04' }, { key: '05', value: '05' },
          { key: '06', value: '06' }, { key: '07', value: '07' }, { key: '08', value: '08' }, { key: '09', value: '09' }, { key: '10', value: '10' },
          { key: '11', value: '11' }, { key: '12', value: '12' }, { key: '13', value: '13' }, { key: '14', value: '14' }, { key: '15', value: '15' },
          { key: '16', value: '16' }, { key: '17', value: '17' }, { key: '18', value: '18' }, { key: '19', value: '19' }, { key: '20', value: '20' },
          { key: '21', value: '21' }, { key: '22', value: '22' }, { key: '23', value: '23' }, { key: '24', value: '24' }, { key: '25', value: '25' },
          { key: '26', value: '26' }, { key: '27', value: '27' }, { key: '28', value: '28' }, { key: '29', value: '29' }, { key: '30', value: '30' },
          { key: 'LD', value: 'اليوم الأخير' }
        ],
        months: [
          { key: '01', value: '1' }, { key: '02', value: '2' }, { key: '03', value: '3' }, { key: '04', value: '4' }, { key: '05', value: '5' },
          { key: '06', value: '6' }, { key: '07', value: '7' }, { key: '08', value: '8' }, { key: '09', value: '9' }, { key: '10', value: '10' },
          { key: '11', value: '11' }, { key: '12', value: '12' }
        ]        
      }
    },
  },
};
