export class HeaderSet {
    Euser: String = "";
    Fbguid: String = "";
    Fbnumx: String = "";
    Fbstax: String = "";
    Fbustx: String = "";
    Gpartx: String = "";
    Langx: String = "";
    Operationx: String = "";
    PortalUsrx: String = "";
    Srcidentifyx: String = "";
    StepNumberx: String = "";
    Abpkindold: String = "";
    Abtyp: String = "";
    Accmethod: String = "";
    Acomcsbd: String = "";
    Acomcsfd: String = "";
    Acsactivitydet: String = "";
    Acsbankdet: String = "";
    Acscontactper: String = "";
    Acsfinancialdet: String = "";
    Acsiddet: String = "";
    Acsperdet: String = "";
    Acsresidence: String = "";
    Acsresidensecomp: String = "";
    Acsshin: String = "";
    Addatt1: String = "";
    Addatt2: String = "";
    Aoldappno: String = "";
    Areact: boolean;
    Assignme: String = "";
    Atype: String = "";
    Augrp: String = "";
    Aupdaterequired: String = "";
    Autoappfg: String = "";
    Birthcity: String = "";
    Birthdt: any;
    Birthdtc: String = "";
    Birthland: String = "";
    Birthregion: String = "";
    Bpkind: String = "";
    Branchx: String = "";
    Caltp: String = "";
    Capamt: number;
    Capregdt: any;
    Chkfg: String = "";
    Citizen: String = "";
    Commdt: any;
    Crexpdt: any;
    DataVersion: String = "";
    Decatt: String = "";
    Decconno: String = "";
    Decdate: any;
    Decdesignation: String = "";
    Decfg: String = "";
    Decname: String = "";
    Draftfg: String = "";
    FamilyName: String = "";
    FatherName: String = "";
    Fbsta: String = "";
    Fbust: String = "";
    Fdcalender: String = "";
    Fdcalold: String = "";
    Fdconfirm: String = "";
    Fdday: String = "";
    Fdenddt: any;
    Fdmonth: String = "";
    Fdnewtaxdt: any;
    Fdtypold: String = "";
    Forcapitalearn: number;
    FormGuid: String = "";
    Forpartnershare: number;
    Forprofitshare: number;
    ForUser: String = "";
    Forward: String = "";
    Forwardx: String = "";
    FullName: String = "";
    Govttp: String = "";
    Gpart: String = "";
    GrandfatherName: String = "";
    Idatt: String = "";
    Initials: String = "";
    Maincr: String = "";
    Mandt: String = "";
    Mandtx: String = "";
    Mobno: String = "";
    NameFirst: String = "";
    NameLast: String = "";
    NameOrg1: String = "";
    NameOrg2: String = "";
    Natio: String = "";
    Ngotp: String = "";
    Officerx: String = "";
    Orgforresident: String = "";
    Orgforresidentoptions: String = "";
    Orgnonresident: String = "";
    Orgnonresidentactivity: String = "";
    Orgnonresidentoptions: String = "";
    Orgresidence: String = "";
    Orgresidentprofessional: String = "";
    Passatt: String = "";
    Qsrvfg: String = "";
    Regtype: String = "";
    Rentatt: String = "";
    Residence: String = "";
    ReturnIdx: String = "";
    Sacapitalearn: number;
    Sapartnershare: number;
    Saprofitshare: number;
    Shgpartx: String = "";
    Shguid: String = "";
    Shldfg: String = "";
    Smartregflg: String = "";
    Statusx: String = "";
    Taxtpdetermination: String = "";
    Topmgatt: String = "";
    Tpnationality: String = "";
    Tpresidence: String = "";
    UserTypx: String = "";
    Vkont: String = "";
    Vkontwht: String = "";
    Vtref: String = "";
    Vtrefwht: String = "";
    Xsexf: String = "";
    Xsexm: String = "";

}

