export class OutletSet {
    Actcat: String = "";
    Actnm: String = "";
    Actnm2: String = "";
    Actno: String = "";
    Caltp: String = "";
    ChInd: String = "";
    City1: String = "";
    CityCode: String = "";
    Cmatt: String = "";
    Conatt: String = "";
    Crlicenceno: String = "";
    DataVersion: String = "";
    EndDate: any;
    Fbnumx: String = "";
    FormGuid: String = "";
    Gpartx: String = "";
    Langx: String = "";
    LineNo: number;
    Mandt: String = "";
    Mandtx: String = "";
    Officerx: String = "";
    Oldmst: String = "";
    Operationx: String = "";
    Outdocdreg: String = "";
    PortalUsrx: String = "";
    RankingOrder: String = "00";
    Rentatt: String = "";
    ReturnIdx: String = "";
    StartDate: any;
    StepNumberx: String = "00";
}
